import { ColorTokens, ThemePreset } from '@zaytoon/tokens';

const lightColor: ColorTokens = {
  background: '#ffffff',
  foreground: '#0b1220',
  primary: '#6366f1',
  primaryForeground: '#ffffff',
  destructive: '#dc2626',
  destructiveForeground: '#ffffff',
  border: '#e5e7eb',
  ring: '#6366f1',
  muted: '#f3f4f6',
  mutedForeground: '#6b7280',
};

const darkColor: ColorTokens = {
  background: '#0b1220',
  foreground: '#e5e9f0',
  primary: '#818cf8',
  primaryForeground: '#0b1220',
  destructive: '#f87171',
  destructiveForeground: '#0b1220',
  border: '#1f2937',
  ring: '#818cf8',
  muted: '#111827',
  mutedForeground: '#9ca3af',
};

export const Aurora: ThemePreset = {
  name: 'aurora',
  tokens: {
    color: lightColor,
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
      xl: '1.5rem',
    },
    radius: {
      sm: '0.25rem',
      md: '0.5rem',
      lg: '0.75rem',
      full: '9999px',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSizeSm: '0.875rem',
      fontSizeMd: '1rem',
      fontWeightMedium: '500',
    },
    comp: {
      button: {
        radius: '0.5rem',
        fontWeight: '500',
        focusRing: 'var(--zaytoon-color-ring)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        foregroundDisabled: 'var(--zaytoon-color-muted-foreground)',
        paddingX: { sm: '0.75rem', md: '1rem', lg: '1.25rem' },
        paddingY: { sm: '0.375rem', md: '0.5rem', lg: '0.625rem' },
        fontSize: { sm: '0.8125rem', md: '0.875rem', lg: '1rem' },
        variants: {
          primary: {
            background: 'var(--zaytoon-color-primary)',
            foreground: 'var(--zaytoon-color-primary-foreground)',
            border: 'var(--zaytoon-color-primary)',
          },
          secondary: {
            background: 'var(--zaytoon-color-muted)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'var(--zaytoon-color-muted)',
          },
          outline: {
            background: 'transparent',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'var(--zaytoon-color-border)',
          },
          ghost: {
            background: 'transparent',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'var(--zaytoon-color-destructive)',
            foreground: 'var(--zaytoon-color-destructive-foreground)',
            border: 'var(--zaytoon-color-destructive)',
          },
          link: {
            background: 'transparent',
            foreground: 'var(--zaytoon-color-primary)',
            border: 'transparent',
          },
        },
      },
      input: {
        paddingX: '0.75rem',
        paddingY: '0.5rem',
        radius: '0.5rem',
        fontSize: '0.875rem',
        background: 'var(--zaytoon-color-background)',
        foreground: 'var(--zaytoon-color-foreground)',
        placeholderForeground: 'var(--zaytoon-color-muted-foreground)',
        border: 'var(--zaytoon-color-border)',
        borderHover: 'var(--zaytoon-color-muted-foreground)',
        borderFocus: 'var(--zaytoon-color-ring)',
        focusRing: 'var(--zaytoon-color-ring)',
        borderInvalid: 'var(--zaytoon-color-destructive)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        foregroundDisabled: 'var(--zaytoon-color-muted-foreground)',
      },
      select: {
        paddingX: '0.75rem',
        paddingY: '0.5rem',
        radius: '0.5rem',
        fontSize: '0.875rem',
        background: 'var(--zaytoon-color-background)',
        foreground: 'var(--zaytoon-color-foreground)',
        placeholderForeground: 'var(--zaytoon-color-muted-foreground)',
        border: 'var(--zaytoon-color-border)',
        borderHover: 'var(--zaytoon-color-muted-foreground)',
        borderFocus: 'var(--zaytoon-color-ring)',
        focusRing: 'var(--zaytoon-color-ring)',
        borderInvalid: 'var(--zaytoon-color-destructive)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        foregroundDisabled: 'var(--zaytoon-color-muted-foreground)',
        panelBackground: 'var(--zaytoon-color-background)',
        panelBorder: 'var(--zaytoon-color-border)',
        panelShadow: '0 4px 16px color-mix(in srgb, black 15%, transparent)',
        optionForeground: 'var(--zaytoon-color-foreground)',
        optionBackgroundHover: 'var(--zaytoon-color-muted)',
        optionBackgroundSelected: 'var(--zaytoon-color-primary)',
        optionForegroundSelected: 'var(--zaytoon-color-primary-foreground)',
      },
      switch: {
        trackPadding: '0.125rem',
        trackBorderWidth: '1px',
        radius: 'var(--zaytoon-radius-full)',
        background: 'var(--zaytoon-color-muted)',
        backgroundChecked: 'var(--zaytoon-color-primary)',
        border: 'var(--zaytoon-color-border)',
        borderChecked: 'var(--zaytoon-color-primary)',
        thumbBackground: 'var(--zaytoon-color-background)',
        focusRing: 'var(--zaytoon-color-ring)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        transitionDuration: '0.15s',
        trackWidth: { sm: '2rem', md: '2.75rem', lg: '3.5rem' },
        trackHeight: { sm: '1.125rem', md: '1.5rem', lg: '1.875rem' },
        thumbSize: { sm: '0.875rem', md: '1.125rem', lg: '1.5rem' },
      },
      checkbox: {
        radius: '0.25rem',
        border: 'var(--zaytoon-color-border)',
        borderChecked: 'var(--zaytoon-color-primary)',
        background: 'var(--zaytoon-color-background)',
        backgroundChecked: 'var(--zaytoon-color-primary)',
        foregroundChecked: 'var(--zaytoon-color-primary-foreground)',
        focusRing: 'var(--zaytoon-color-ring)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        borderDisabled: 'var(--zaytoon-color-border)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      radio: {
        border: 'var(--zaytoon-color-border)',
        borderChecked: 'var(--zaytoon-color-primary)',
        background: 'var(--zaytoon-color-background)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        borderDisabled: 'var(--zaytoon-color-border)',
        dotBackground: 'var(--zaytoon-color-primary)',
        focusRing: 'var(--zaytoon-color-ring)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      popover: {
        background: 'var(--zaytoon-color-background)',
        border: 'var(--zaytoon-color-border)',
        shadow: '0 4px 16px color-mix(in srgb, black 15%, transparent)',
        radius: '0.5rem',
        foreground: 'var(--zaytoon-color-foreground)',
        paddingX: '1rem',
        paddingY: '0.75rem',
      },
      tooltip: {
        background: 'var(--zaytoon-color-foreground)',
        foreground: 'var(--zaytoon-color-background)',
        radius: '0.375rem',
        paddingX: '0.5rem',
        paddingY: '0.25rem',
        fontSize: 'var(--zaytoon-typography-font-size-sm)',
      },
      skeleton: {
        background: 'var(--zaytoon-color-muted)',
        shimmer: 'color-mix(in srgb, var(--zaytoon-color-muted-foreground) 20%, transparent)',
        radius: '0.375rem',
      },
      avatar: {
        background: 'var(--zaytoon-color-muted)',
        foreground: 'var(--zaytoon-color-foreground)',
        radius: '0.5rem',
        statusOnline: '#22c55e',
        statusAway: '#f59e0b',
        statusBusy: '#ef4444',
        statusOffline: '#9ca3af',
        size: { sm: '1.75rem', md: '2.5rem', lg: '3.5rem', xl: '5rem' },
        fontSize: { sm: '0.625rem', md: '0.875rem', lg: '1.125rem', xl: '1.5rem' },
      },
      tag: {
        radius: '0.375rem',
        fontSize: 'var(--zaytoon-typography-font-size-sm)',
        paddingX: '0.5rem',
        paddingY: '0.125rem',
        variants: {
          default: {
            background: 'var(--zaytoon-color-muted)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'color-mix(in srgb, var(--zaytoon-color-primary) 15%, transparent)',
            foreground: 'var(--zaytoon-color-primary)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--zaytoon-color-muted)',
            foreground: 'var(--zaytoon-color-muted-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'color-mix(in srgb, var(--zaytoon-color-destructive) 15%, transparent)',
            foreground: 'var(--zaytoon-color-destructive)',
            border: 'transparent',
          },
          outline: {
            background: 'transparent',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'var(--zaytoon-color-border)',
          },
        },
      },
      breadcrumb: {
        foreground: 'var(--zaytoon-color-muted-foreground)',
        currentForeground: 'var(--zaytoon-color-foreground)',
        separatorColor: 'var(--zaytoon-color-muted-foreground)',
        fontSize: 'var(--zaytoon-typography-font-size-sm)',
        gap: '0.375rem',
      },
      badge: {
        size: '1.25rem',
        dotSize: '0.625rem',
        fontSize: '0.6875rem',
        ringColor: 'var(--zaytoon-color-background)',
        variants: {
          default: {
            background: 'var(--zaytoon-color-muted)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'var(--zaytoon-color-primary)',
            foreground: 'var(--zaytoon-color-primary-foreground)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--zaytoon-color-muted)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'var(--zaytoon-color-destructive)',
            foreground: 'var(--zaytoon-color-destructive-foreground)',
            border: 'transparent',
          },
          outline: {
            background: 'var(--zaytoon-color-background)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'var(--zaytoon-color-border)',
          },
        },
      },
      pagination: {
        radius: '0.375rem',
        gap: '0.25rem',
        size: '2.25rem',
        border: 'var(--zaytoon-color-border)',
        background: 'transparent',
        foreground: 'var(--zaytoon-color-foreground)',
        backgroundHover: 'var(--zaytoon-color-muted)',
        backgroundActive: 'var(--zaytoon-color-primary)',
        foregroundActive: 'var(--zaytoon-color-primary-foreground)',
        foregroundDisabled: 'var(--zaytoon-color-muted-foreground)',
      },
      rating: {
        filledColor: '#f59e0b',
        emptyColor: 'var(--zaytoon-color-border)',
        gap: '0',
        size: { sm: '1rem', md: '1.5rem', lg: '2rem' },
      },
      accordion: {
        border: 'var(--zaytoon-color-border)',
        radius: 'var(--zaytoon-radius-md)',
        headerBackground: 'transparent',
        headerBackgroundHover: 'var(--zaytoon-color-muted)',
        headerForeground: 'var(--zaytoon-color-foreground)',
        panelBackground: 'transparent',
        panelForeground: 'var(--zaytoon-color-muted-foreground)',
        fontSize: 'var(--zaytoon-typography-font-size-sm)',
        fontWeight: 'var(--zaytoon-typography-font-weight-medium)',
        paddingX: 'var(--zaytoon-spacing-md)',
        paddingY: 'var(--zaytoon-spacing-sm)',
      },
      tabs: {
        border: 'var(--zaytoon-color-border)',
        gap: 'var(--zaytoon-spacing-md)',
        foreground: 'var(--zaytoon-color-muted-foreground)',
        foregroundActive: 'var(--zaytoon-color-primary)',
        foregroundDisabled: 'var(--zaytoon-color-muted-foreground)',
        indicatorColor: 'var(--zaytoon-color-primary)',
        indicatorThickness: '2px',
        fontSize: 'var(--zaytoon-typography-font-size-sm)',
        fontWeight: 'var(--zaytoon-typography-font-weight-medium)',
        paddingX: 'var(--zaytoon-spacing-md)',
        paddingY: 'var(--zaytoon-spacing-sm)',
      },
      stepper: {
        circleSize: '2rem',
        circleBorder: 'var(--zaytoon-color-border)',
        circleBackground: 'var(--zaytoon-color-background)',
        circleForeground: 'var(--zaytoon-color-muted-foreground)',
        circleBackgroundActive: 'var(--zaytoon-color-primary)',
        circleForegroundActive: 'var(--zaytoon-color-primary-foreground)',
        circleBackgroundCompleted: 'var(--zaytoon-color-primary)',
        circleForegroundCompleted: 'var(--zaytoon-color-primary-foreground)',
        connectorColor: 'var(--zaytoon-color-border)',
        connectorColorCompleted: 'var(--zaytoon-color-primary)',
        labelColor: 'var(--zaytoon-color-muted-foreground)',
        labelColorActive: 'var(--zaytoon-color-foreground)',
        descriptionColor: 'var(--zaytoon-color-muted-foreground)',
        fontSize: 'var(--zaytoon-typography-font-size-sm)',
        gap: 'var(--zaytoon-spacing-sm)',
      },
      slider: {
        trackSize: '0.375rem',
        trackColor: 'var(--zaytoon-color-muted)',
        fillColor: 'var(--zaytoon-color-primary)',
        thumbSize: '1.125rem',
        thumbBackground: 'var(--zaytoon-color-background)',
        thumbBorder: 'var(--zaytoon-color-primary)',
        thumbBorderFocus: 'var(--zaytoon-color-ring)',
        tickColor: 'var(--zaytoon-color-border)',
        tickSize: '0.25rem',
        bubbleBackground: 'var(--zaytoon-color-foreground)',
        bubbleForeground: 'var(--zaytoon-color-background)',
      },
      colorPicker: {
        svAreaSize: '12rem',
        hueTrackHeight: '0.75rem',
        thumbSize: '1rem',
        hueThumbWidth: '0.75rem',
        presetSize: '1.5rem',
        presetGap: '0.375rem',
        presetBorder: 'var(--zaytoon-color-border)',
        presetBorderSelected: 'var(--zaytoon-color-primary)',
      },
      datePicker: {
        daySize: '2.25rem',
        fontSize: 'var(--zaytoon-typography-font-size-sm)',
        dayForeground: 'var(--zaytoon-color-foreground)',
        dayForegroundOutsideMonth: 'var(--zaytoon-color-muted-foreground)',
        dayBackgroundHover: 'var(--zaytoon-color-muted)',
        dayBackgroundSelected: 'var(--zaytoon-color-primary)',
        dayForegroundSelected: 'var(--zaytoon-color-primary-foreground)',
        dayBorderToday: 'var(--zaytoon-color-primary)',
        navBackgroundHover: 'var(--zaytoon-color-muted)',
        weekdayForeground: 'var(--zaytoon-color-muted-foreground)',
        monthLabelForeground: 'var(--zaytoon-color-foreground)',
      },
      carousel: {
        radius: 'var(--zaytoon-radius-lg)',
        arrowSize: '2.5rem',
        arrowBackground: 'rgb(0 0 0 / 0.4)',
        arrowBackgroundHover: 'rgb(0 0 0 / 0.6)',
        arrowColor: '#fff',
        dotSize: '0.5rem',
        dotColor: 'var(--zaytoon-color-border)',
        dotColorActive: 'var(--zaytoon-color-primary)',
        dotGap: 'var(--zaytoon-spacing-xs)',
      },
      toast: {
        radius: 'var(--zaytoon-radius-md)',
        shadow: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        paddingX: 'var(--zaytoon-spacing-md)',
        paddingY: 'var(--zaytoon-spacing-sm)',
        gap: 'var(--zaytoon-spacing-sm)',
        maxWidth: '24rem',
        variants: {
          default: {
            background: 'var(--zaytoon-color-background)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'var(--zaytoon-color-border)',
            iconColor: 'var(--zaytoon-color-muted-foreground)',
          },
          success: {
            background: 'var(--zaytoon-color-background)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: '#22c55e',
            iconColor: '#22c55e',
          },
          error: {
            background: 'var(--zaytoon-color-background)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'var(--zaytoon-color-destructive)',
            iconColor: 'var(--zaytoon-color-destructive)',
          },
          warning: {
            background: 'var(--zaytoon-color-background)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: '#f59e0b',
            iconColor: '#f59e0b',
          },
          info: {
            background: 'var(--zaytoon-color-background)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: '#3b82f6',
            iconColor: '#3b82f6',
          },
        },
      },
      fileUpload: {
        border: 'var(--zaytoon-color-border)',
        borderDragOver: 'var(--zaytoon-color-primary)',
        background: 'transparent',
        backgroundDragOver: 'var(--zaytoon-color-muted)',
        radius: 'var(--zaytoon-radius-lg)',
        iconColor: 'var(--zaytoon-color-muted-foreground)',
        hintColor: 'var(--zaytoon-color-foreground)',
        acceptColor: 'var(--zaytoon-color-muted-foreground)',
        itemBackground: 'var(--zaytoon-color-muted)',
        itemBorder: 'var(--zaytoon-color-border)',
        itemRadius: 'var(--zaytoon-radius-md)',
        thumbSize: '2.5rem',
        rejectionColor: 'var(--zaytoon-color-destructive)',
      },
      dialog: {
        backdropColor: 'rgb(0 0 0 / 0.5)',
        panelBackground: 'var(--zaytoon-color-background)',
        panelBorder: 'var(--zaytoon-color-border)',
        radius: 'var(--zaytoon-radius-lg)',
        shadow: '0 20px 25px -5px rgb(0 0 0 / 0.15), 0 8px 10px -6px rgb(0 0 0 / 0.15)',
        headerBorder: 'var(--zaytoon-color-border)',
        footerBorder: 'var(--zaytoon-color-border)',
        titleFontSize: '1.125rem',
        titleFontWeight: 'var(--zaytoon-typography-font-weight-medium)',
        padding: 'var(--zaytoon-spacing-lg)',
        widths: { sm: '24rem', md: '32rem', lg: '48rem', full: 'calc(100vw - 2rem)' },
      },
    },
  },
  darkColor,
  icons: {
    loading: { type: 'ng-icon', name: 'lucideLoaderCircle' },
    chevronDown: { type: 'ng-icon', name: 'lucideChevronDown' },
    clear: { type: 'ng-icon', name: 'lucideX' },
    passwordShow: { type: 'ng-icon', name: 'lucideEye' },
    passwordHide: { type: 'ng-icon', name: 'lucideEyeOff' },
    checkboxCheck: { type: 'ng-icon', name: 'lucideCheck' },
    checkboxIndeterminate: { type: 'ng-icon', name: 'lucideMinus' },
    search: { type: 'ng-icon', name: 'lucideSearch' },
    plus: { type: 'ng-icon', name: 'lucidePlus' },
    minus: { type: 'ng-icon', name: 'lucideMinus' },
    avatarFallback: { type: 'ng-icon', name: 'lucideUser' },
    rating: { type: 'ng-icon', name: 'lucideStar' },
    upload: { type: 'ng-icon', name: 'lucideUpload' },
    file: { type: 'ng-icon', name: 'lucideFile' },
    toastSuccess: { type: 'ng-icon', name: 'lucideCircleCheck' },
    toastError: { type: 'ng-icon', name: 'lucideCircleX' },
    toastWarning: { type: 'ng-icon', name: 'lucideTriangleAlert' },
    toastInfo: { type: 'ng-icon', name: 'lucideInfo' },
  },
};
