import { ColorTokens, ThemePreset } from '@zaytoon/tokens';

const lightColor: ColorTokens = {
  background: '#ffffff',
  foreground: '#0b1220',
  primary: '#6366f1',
  primaryForeground: '#ffffff',
  destructive: '#dc2626',
  destructiveForeground: '#ffffff',
  border: '#e5e7eb',
  ring: '#6366f1',
  muted: '#f3f4f6',
  mutedForeground: '#6b7280',
};

const darkColor: ColorTokens = {
  background: '#0b1220',
  foreground: '#e5e9f0',
  primary: '#818cf8',
  primaryForeground: '#0b1220',
  destructive: '#f87171',
  destructiveForeground: '#0b1220',
  border: '#1f2937',
  ring: '#818cf8',
  muted: '#111827',
  mutedForeground: '#9ca3af',
};

export const Aurora: ThemePreset = {
  name: 'aurora',
  tokens: {
    color: lightColor,
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
      xl: '1.5rem',
    },
    radius: {
      sm: '0.25rem',
      md: '0.5rem',
      lg: '0.75rem',
      full: '9999px',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSizeSm: '0.875rem',
      fontSizeMd: '1rem',
      fontWeightMedium: '500',
    },
    comp: {
      button: {
        radius: '0.5rem',
        fontWeight: '500',
        focusRing: 'var(--zaytoon-color-ring)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        foregroundDisabled: 'var(--zaytoon-color-muted-foreground)',
        paddingX: { sm: '0.75rem', md: '1rem', lg: '1.25rem' },
        paddingY: { sm: '0.375rem', md: '0.5rem', lg: '0.625rem' },
        fontSize: { sm: '0.8125rem', md: '0.875rem', lg: '1rem' },
        variants: {
          primary: {
            background: 'var(--zaytoon-color-primary)',
            foreground: 'var(--zaytoon-color-primary-foreground)',
            border: 'var(--zaytoon-color-primary)',
          },
          secondary: {
            background: 'var(--zaytoon-color-muted)',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'var(--zaytoon-color-muted)',
          },
          outline: {
            background: 'transparent',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'var(--zaytoon-color-border)',
          },
          ghost: {
            background: 'transparent',
            foreground: 'var(--zaytoon-color-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'var(--zaytoon-color-destructive)',
            foreground: 'var(--zaytoon-color-destructive-foreground)',
            border: 'var(--zaytoon-color-destructive)',
          },
          link: {
            background: 'transparent',
            foreground: 'var(--zaytoon-color-primary)',
            border: 'transparent',
          },
        },
      },
      input: {
        paddingX: '0.75rem',
        paddingY: '0.5rem',
        radius: '0.5rem',
        fontSize: '0.875rem',
        background: 'var(--zaytoon-color-background)',
        foreground: 'var(--zaytoon-color-foreground)',
        placeholderForeground: 'var(--zaytoon-color-muted-foreground)',
        border: 'var(--zaytoon-color-border)',
        borderHover: 'var(--zaytoon-color-muted-foreground)',
        borderFocus: 'var(--zaytoon-color-ring)',
        focusRing: 'var(--zaytoon-color-ring)',
        borderInvalid: 'var(--zaytoon-color-destructive)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        foregroundDisabled: 'var(--zaytoon-color-muted-foreground)',
      },
      select: {
        paddingX: '0.75rem',
        paddingY: '0.5rem',
        radius: '0.5rem',
        fontSize: '0.875rem',
        background: 'var(--zaytoon-color-background)',
        foreground: 'var(--zaytoon-color-foreground)',
        placeholderForeground: 'var(--zaytoon-color-muted-foreground)',
        border: 'var(--zaytoon-color-border)',
        borderHover: 'var(--zaytoon-color-muted-foreground)',
        borderFocus: 'var(--zaytoon-color-ring)',
        focusRing: 'var(--zaytoon-color-ring)',
        borderInvalid: 'var(--zaytoon-color-destructive)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        foregroundDisabled: 'var(--zaytoon-color-muted-foreground)',
        panelBackground: 'var(--zaytoon-color-background)',
        panelBorder: 'var(--zaytoon-color-border)',
        panelShadow: '0 4px 16px color-mix(in srgb, black 15%, transparent)',
        optionForeground: 'var(--zaytoon-color-foreground)',
        optionBackgroundHover: 'var(--zaytoon-color-muted)',
        optionBackgroundSelected: 'var(--zaytoon-color-primary)',
        optionForegroundSelected: 'var(--zaytoon-color-primary-foreground)',
      },
      switch: {
        trackPadding: '0.125rem',
        trackBorderWidth: '1px',
        radius: 'var(--zaytoon-radius-full)',
        background: 'var(--zaytoon-color-muted)',
        backgroundChecked: 'var(--zaytoon-color-primary)',
        border: 'var(--zaytoon-color-border)',
        borderChecked: 'var(--zaytoon-color-primary)',
        thumbBackground: 'var(--zaytoon-color-background)',
        focusRing: 'var(--zaytoon-color-ring)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        transitionDuration: '0.15s',
        trackWidth: { sm: '2rem', md: '2.75rem', lg: '3.5rem' },
        trackHeight: { sm: '1.125rem', md: '1.5rem', lg: '1.875rem' },
        thumbSize: { sm: '0.875rem', md: '1.125rem', lg: '1.5rem' },
      },
      checkbox: {
        radius: '0.25rem',
        border: 'var(--zaytoon-color-border)',
        borderChecked: 'var(--zaytoon-color-primary)',
        background: 'var(--zaytoon-color-background)',
        backgroundChecked: 'var(--zaytoon-color-primary)',
        foregroundChecked: 'var(--zaytoon-color-primary-foreground)',
        focusRing: 'var(--zaytoon-color-ring)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        borderDisabled: 'var(--zaytoon-color-border)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      radio: {
        border: 'var(--zaytoon-color-border)',
        borderChecked: 'var(--zaytoon-color-primary)',
        background: 'var(--zaytoon-color-background)',
        backgroundDisabled: 'var(--zaytoon-color-muted)',
        borderDisabled: 'var(--zaytoon-color-border)',
        dotBackground: 'var(--zaytoon-color-primary)',
        focusRing: 'var(--zaytoon-color-ring)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
    },
  },
  darkColor,
  icons: {
    loading: { type: 'ng-icon', name: 'lucideLoaderCircle' },
    chevronDown: { type: 'ng-icon', name: 'lucideChevronDown' },
    clear: { type: 'ng-icon', name: 'lucideX' },
    passwordShow: { type: 'ng-icon', name: 'lucideEye' },
    passwordHide: { type: 'ng-icon', name: 'lucideEyeOff' },
    checkboxCheck: { type: 'ng-icon', name: 'lucideCheck' },
    checkboxIndeterminate: { type: 'ng-icon', name: 'lucideMinus' },
  },
};
