import { IconTokens } from './icon-tokens';

/**
 * The SemiUI design-token type vocabulary.
 *
 * Tokens are authored in three layers, and each layer may only reference the layer(s) above it:
 *
 *     Primitive tokens   raw design values -- `blue.500`, `spacing.md`, `white`
 *           |
 *     Semantic tokens    what a value *means* -- `primary`, `destructive`, `mutedForeground`
 *           |
 *     Component tokens   what a component uses -- `button.variants.primary.background`
 *           |
 *     CSS variables      generated by the engine; preset authors never write these by hand
 *
 * A preset therefore describes design decisions, never CSS variable names. `{path}` references
 * (see `TokenValue`) are what connect the layers, and the engine turns each one into a live
 * `var()` reference at generation time -- see `buildThemeVars` in `token-engine.ts`.
 */

/**
 * A single token value. Always a string, and it can be any of:
 *
 * - a token reference -- `'{blue.500}'`, `'{primary}'`, `'{typography.fontSize.sm}'`
 * - a raw CSS value -- `'0.5rem'`, `'transparent'`, `'0 8px 24px rgb(15 23 42 / 0.10)'`
 * - a raw CSS value with references embedded in it --
 *   `'color-mix(in srgb, {primary} 15%, transparent)'`
 * - an explicit CSS variable reference -- `'var(--some-app-level-var)'`, for the rare case where
 *   a preset genuinely needs to point at something outside the token system
 *
 * Nothing about the type changes based on which form you pick; the engine tells them apart by
 * looking for `{...}` groups. Whole-object references (`'{blue}'` pointing at a full color scale)
 * are also supported wherever a subtree is expected -- see `PaletteTokens`.
 */
export type TokenValue = string;

/** An arbitrarily nested tree of token values. */
export type TokenTree = { [key: string]: TokenValue | TokenTree };

/** The 11 steps of a SemiUI color ramp -- 50 is the lightest tint, 950 the darkest shade. */
export type ColorShade = 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 950;

/**
 * An 11-step tint/shade ramp. 500 is conventionally the base color a scale is built around, so
 * `generateColorScale(base)[500] === base`.
 */
export type ColorScale = { [K in ColorShade]: TokenValue };

// ---------------------------------------------------------------------------------------------
// Layer 1 -- primitives
// ---------------------------------------------------------------------------------------------

/**
 * Raw design values, with no meaning attached. A primitive is never used directly by a component;
 * it exists so semantic tokens have something to point at, and so two semantic tokens that happen
 * to be the same color are the *same token* rather than two copies of one literal.
 *
 * Colors are usually authored as full `ColorScale` ramps (`blue`, `slate`, ...) plus a handful of
 * standalone constants (`white`, `black`, `transparent`), but the shape is deliberately open: any
 * nested tree of values works, and each leaf becomes referenceable by its own path.
 */
export type PrimitiveTokens = {
  white?: TokenValue;
  black?: TokenValue;
  transparent?: TokenValue;
  [name: string]: TokenValue | ColorScale | TokenTree | undefined;
};

// ---------------------------------------------------------------------------------------------
// Layer 2 -- semantics
// ---------------------------------------------------------------------------------------------

/**
 * The status vocabulary shared across Button/Tag/Badge and friends. `danger`/`error`/`warn` are
 * aliases -- they resolve to `destructive`/`destructive`/`warning` rather than carrying their own
 * color, so changing `destructive` changes all of them.
 */
export type SemanticColorTokens = {
  /** Page/surface background. */
  background: TokenValue;
  /** Default text color drawn on `background`. */
  foreground: TokenValue;

  primary: TokenValue;
  primaryForeground: TokenValue;
  secondary: TokenValue;
  secondaryForeground: TokenValue;
  success: TokenValue;
  successForeground: TokenValue;
  info: TokenValue;
  infoForeground: TokenValue;
  warning: TokenValue;
  warningForeground: TokenValue;
  destructive: TokenValue;
  destructiveForeground: TokenValue;
  help: TokenValue;
  helpForeground: TokenValue;
  /** Maximum-contrast ink against the current surface -- inverts between light and dark mode. */
  contrast: TokenValue;
  contrastForeground: TokenValue;

  /** A recessive surface: input fills, striped rows, disabled backgrounds. */
  muted: TokenValue;
  /** Readable ink designed to pair with `muted` -- secondary/placeholder text. */
  mutedForeground: TokenValue;
  border: TokenValue;
  /** Focus-ring color. Normally an alias of `primary`. */
  ring: TokenValue;

  /** Alias of `destructive`, for PrimeNG-style naming. */
  danger: TokenValue;
  dangerForeground: TokenValue;
  /** Alias of `destructive`, for the Toast/validation vocabulary. */
  error: TokenValue;
  errorForeground: TokenValue;
  /** Alias of `warning`, for PrimeNG-style naming. */
  warn: TokenValue;
  warnForeground: TokenValue;
};

/**
 * Full ramps backing the semantic colors. Usually a whole-object reference into a primitive scale
 * (`primary: '{blue}'`), which expands shade-by-shade, but individual shades can be authored or
 * overridden too. These are what the Tailwind bridge exposes as `primary-50` .. `primary-950`.
 */
export type PaletteTokens = { [scale: string]: TokenValue | Partial<ColorScale> };

export type SpacingTokens = {
  xs: TokenValue;
  sm: TokenValue;
  md: TokenValue;
  lg: TokenValue;
  xl: TokenValue;
};

export type RadiusTokens = {
  sm: TokenValue;
  md: TokenValue;
  lg: TokenValue;
  full: TokenValue;
};

export type TypographyTokens = {
  fontFamily: TokenValue;
  fontSize: { sm: TokenValue; md: TokenValue } & { [step: string]: TokenValue };
  fontWeight: { medium: TokenValue } & { [step: string]: TokenValue };
};

/**
 * What values *mean*. Colors sit flat at the top level (`primary`, `border`, ...); the non-color
 * scales live in their own named groups so they read -- and generate -- as their own namespaces.
 *
 * Every value here should reference a primitive rather than repeat a literal, so that changing one
 * primitive changes everything downstream of it.
 */
export type SemanticTokens = SemanticColorTokens & {
  palette: PaletteTokens;
  spacing: SpacingTokens;
  radius: RadiusTokens;
  typography: TypographyTokens;
};

// ---------------------------------------------------------------------------------------------
// Layer 3 -- components
// ---------------------------------------------------------------------------------------------

export type ButtonSize = 'sm' | 'md' | 'lg';
export type AvatarSize = 'sm' | 'md' | 'lg' | 'xl';
export type DialogSize = 'sm' | 'md' | 'lg' | 'full';

/** Shared status vocabulary across Button/Tag/Badge, on top of each component's own style-only
 * variants (outline/ghost/link for Button, default/outline for Tag/Badge). */
export type Severity = 'primary' | 'secondary' | 'success' | 'info' | 'warn' | 'help' | 'danger' | 'contrast';
export type ButtonVariant = Severity | 'destructive' | 'link';
export type TagVariant = Severity | 'default' | 'destructive' | 'outline';
export type ToastVariant = 'default' | 'success' | 'error' | 'warning' | 'info';

export type SurfaceVariantTokens = {
  background: TokenValue;
  foreground: TokenValue;
  border: TokenValue;
};

export type ToastVariantTokens = SurfaceVariantTokens & {
  iconColor: TokenValue;
};

export type ButtonTokens = {
  radius: TokenValue;
  fontWeight: TokenValue;
  focusRing: TokenValue;
  backgroundDisabled: TokenValue;
  foregroundDisabled: TokenValue;
  paddingX: Record<ButtonSize, TokenValue>;
  paddingY: Record<ButtonSize, TokenValue>;
  fontSize: Record<ButtonSize, TokenValue>;
  variants: Record<ButtonVariant, SurfaceVariantTokens>;
};

/** Input and Select share this field set; Select adds its own panel/option tokens on top. */
export type FieldTokens = {
  paddingX: TokenValue;
  paddingY: TokenValue;
  radius: TokenValue;
  fontSize: TokenValue;
  background: TokenValue;
  foreground: TokenValue;
  placeholderForeground: TokenValue;
  border: TokenValue;
  borderHover: TokenValue;
  borderFocus: TokenValue;
  focusRing: TokenValue;
  borderInvalid: TokenValue;
  backgroundDisabled: TokenValue;
  foregroundDisabled: TokenValue;
};

export type SelectTokens = FieldTokens & {
  panelBackground: TokenValue;
  panelBorder: TokenValue;
  panelShadow: TokenValue;
  /** Shared by Cascade Select's and Auto Complete's panels (both reuse `select.*` throughout):
   * the option list's `max-height` before it scrolls. */
  panelMaxHeight: TokenValue;
  optionForeground: TokenValue;
  optionBackgroundHover: TokenValue;
  optionBackgroundSelected: TokenValue;
  optionForegroundSelected: TokenValue;
};

/**
 * Per-component tokens. A component token exists for one of two reasons: it points a component at
 * a semantic decision (`background: '{primary}'`), or it carries a value that is genuinely local
 * to that component and has no design-system meaning (`dialog.widths.md`). Both are legitimate --
 * see the SemiUI theming docs. What a component token should *not* be is a duplicated copy of a
 * semantic value.
 *
 * The index signature at the end lets a preset add tokens for components SemiUI doesn't ship.
 */
export type ComponentTokens = {
  button: ButtonTokens;
  input: FieldTokens;
  select: SelectTokens;
  switch: {
    trackPadding: TokenValue;
    trackBorderWidth: TokenValue;
    radius: TokenValue;
    background: TokenValue;
    backgroundChecked: TokenValue;
    border: TokenValue;
    borderChecked: TokenValue;
    thumbBackground: TokenValue;
    focusRing: TokenValue;
    backgroundDisabled: TokenValue;
    transitionDuration: TokenValue;
    trackWidth: Record<ButtonSize, TokenValue>;
    trackHeight: Record<ButtonSize, TokenValue>;
    thumbSize: Record<ButtonSize, TokenValue>;
  };
  checkbox: {
    radius: TokenValue;
    border: TokenValue;
    borderChecked: TokenValue;
    background: TokenValue;
    backgroundChecked: TokenValue;
    foregroundChecked: TokenValue;
    focusRing: TokenValue;
    backgroundDisabled: TokenValue;
    borderDisabled: TokenValue;
    size: Record<ButtonSize, TokenValue>;
  };
  radio: {
    border: TokenValue;
    borderChecked: TokenValue;
    background: TokenValue;
    backgroundDisabled: TokenValue;
    borderDisabled: TokenValue;
    dotBackground: TokenValue;
    focusRing: TokenValue;
    size: Record<ButtonSize, TokenValue>;
  };
  popover: {
    background: TokenValue;
    border: TokenValue;
    shadow: TokenValue;
    radius: TokenValue;
    foreground: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
  };
  tooltip: {
    background: TokenValue;
    foreground: TokenValue;
    radius: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
    fontSize: TokenValue;
  };
  skeleton: {
    background: TokenValue;
    shimmer: TokenValue;
    radius: TokenValue;
  };
  avatar: {
    background: TokenValue;
    foreground: TokenValue;
    radius: TokenValue;
    statusOnline: TokenValue;
    statusAway: TokenValue;
    statusBusy: TokenValue;
    statusOffline: TokenValue;
    size: Record<AvatarSize, TokenValue>;
    fontSize: Record<AvatarSize, TokenValue>;
  };
  tag: {
    radius: TokenValue;
    fontSize: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
    variants: Record<TagVariant, SurfaceVariantTokens>;
  };
  breadcrumb: {
    foreground: TokenValue;
    currentForeground: TokenValue;
    separatorColor: TokenValue;
    fontSize: TokenValue;
    gap: TokenValue;
  };
  badge: {
    size: TokenValue;
    dotSize: TokenValue;
    fontSize: TokenValue;
    ringColor: TokenValue;
    variants: Record<TagVariant, SurfaceVariantTokens>;
  };
  pagination: {
    radius: TokenValue;
    gap: TokenValue;
    size: TokenValue;
    border: TokenValue;
    background: TokenValue;
    foreground: TokenValue;
    backgroundHover: TokenValue;
    backgroundActive: TokenValue;
    foregroundActive: TokenValue;
    foregroundDisabled: TokenValue;
  };
  rating: {
    filledColor: TokenValue;
    emptyColor: TokenValue;
    gap: TokenValue;
    size: Record<ButtonSize, TokenValue>;
  };
  accordion: {
    border: TokenValue;
    radius: TokenValue;
    headerBackground: TokenValue;
    headerBackgroundHover: TokenValue;
    headerForeground: TokenValue;
    panelBackground: TokenValue;
    panelForeground: TokenValue;
    fontSize: TokenValue;
    fontWeight: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
  };
  tabs: {
    border: TokenValue;
    gap: TokenValue;
    foreground: TokenValue;
    foregroundActive: TokenValue;
    foregroundDisabled: TokenValue;
    indicatorColor: TokenValue;
    indicatorThickness: TokenValue;
    fontSize: TokenValue;
    fontWeight: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
  };
  stepper: {
    circleSize: TokenValue;
    circleBorder: TokenValue;
    circleBackground: TokenValue;
    circleForeground: TokenValue;
    circleBackgroundActive: TokenValue;
    circleForegroundActive: TokenValue;
    circleBackgroundCompleted: TokenValue;
    circleForegroundCompleted: TokenValue;
    connectorColor: TokenValue;
    connectorColorCompleted: TokenValue;
    labelColor: TokenValue;
    labelColorActive: TokenValue;
    descriptionColor: TokenValue;
    fontSize: TokenValue;
    gap: TokenValue;
  };
  slider: {
    trackSize: TokenValue;
    trackColor: TokenValue;
    fillColor: TokenValue;
    thumbSize: TokenValue;
    thumbBackground: TokenValue;
    thumbBorder: TokenValue;
    thumbBorderFocus: TokenValue;
    tickColor: TokenValue;
    tickSize: TokenValue;
    bubbleBackground: TokenValue;
    bubbleForeground: TokenValue;
  };
  chart: {
    gridColor: TokenValue;
    axisLabelColor: TokenValue;
    axisLabelFontSize: TokenValue;
    tooltipBackground: TokenValue;
    tooltipForeground: TokenValue;
    tooltipRadius: TokenValue;
    legendFontSize: TokenValue;
    legendGap: TokenValue;
    lineStrokeWidth: TokenValue;
    areaOpacity: TokenValue;
  };
  table: {
    border: TokenValue;
    radius: TokenValue;
    headerBackground: TokenValue;
    headerForeground: TokenValue;
    rowBackground: TokenValue;
    rowBackgroundStriped: TokenValue;
    rowBackgroundHover: TokenValue;
    rowBackgroundSelected: TokenValue;
    fontSize: TokenValue;
    cellPaddingX: TokenValue;
    cellPaddingY: TokenValue;
    sortIconColor: TokenValue;
    sortIconColorActive: TokenValue;
  };
  colorPicker: {
    svAreaSize: TokenValue;
    hueTrackHeight: TokenValue;
    thumbSize: TokenValue;
    hueThumbWidth: TokenValue;
    presetSize: TokenValue;
    presetGap: TokenValue;
    presetBorder: TokenValue;
    presetBorderSelected: TokenValue;
  };
  datePicker: {
    daySize: TokenValue;
    fontSize: TokenValue;
    dayForeground: TokenValue;
    dayForegroundOutsideMonth: TokenValue;
    dayBackgroundHover: TokenValue;
    dayBackgroundSelected: TokenValue;
    dayForegroundSelected: TokenValue;
    dayBorderToday: TokenValue;
    navBackgroundHover: TokenValue;
    weekdayForeground: TokenValue;
    monthLabelForeground: TokenValue;
  };
  carousel: {
    radius: TokenValue;
    arrowSize: TokenValue;
    arrowBackground: TokenValue;
    arrowBackgroundHover: TokenValue;
    arrowColor: TokenValue;
    dotSize: TokenValue;
    dotColor: TokenValue;
    dotColorActive: TokenValue;
    dotGap: TokenValue;
  };
  toast: {
    radius: TokenValue;
    shadow: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
    gap: TokenValue;
    /** Every toast's width, e.g. `'24rem'`. */
    width: TokenValue;
    /** `backdrop-filter` value applied to every toast, e.g. `'blur(12px)'`. `'none'` disables it.
     * Pairs with translucent variant backgrounds (see `variants.*.background`). */
    blur: TokenValue;
    variants: Record<ToastVariant, ToastVariantTokens>;
  };
  fileUpload: {
    border: TokenValue;
    borderDragOver: TokenValue;
    background: TokenValue;
    backgroundDragOver: TokenValue;
    radius: TokenValue;
    iconColor: TokenValue;
    hintColor: TokenValue;
    acceptColor: TokenValue;
    itemBackground: TokenValue;
    itemBorder: TokenValue;
    itemRadius: TokenValue;
    thumbSize: TokenValue;
    rejectionColor: TokenValue;
  };
  dialog: {
    backdropColor: TokenValue;
    panelBackground: TokenValue;
    panelBorder: TokenValue;
    radius: TokenValue;
    shadow: TokenValue;
    headerBorder: TokenValue;
    footerBorder: TokenValue;
    titleFontSize: TokenValue;
    titleFontWeight: TokenValue;
    padding: TokenValue;
    widths: Record<DialogSize, TokenValue>;
  };
  speedDial: {
    /** Radius of the trigger and of every mini action. `'{radius.full}'` gives the conventional
     * circular FAB; a square-cornered preset sets its own. */
    radius: TokenValue;
    /** Elevation on the trigger and on every mini action. `'none'` for presets that don't use
     * shadow. */
    shadow: TokenValue;
    /** Distance between the trigger and the fan of actions, and between the actions themselves. */
    gap: TokenValue;
    /** Diameter of one mini action, per the Speed Dial's `size`. Kept below the trigger's own size
     * so the FAB stays visually dominant. */
    actionSize: Record<ButtonSize, TokenValue>;
    actionBackground: TokenValue;
    actionForeground: TokenValue;
    actionBorder: TokenValue;
    /** Delay step between consecutive actions in the staggered reveal, e.g. `'40ms'` -- the nth
     * action waits n times this. `'0ms'` reveals them all at once. */
    stagger: TokenValue;
  };
  fullCalendar: {
    navButtonSize: TokenValue;
    navIconSize: TokenValue;
    /** Block-axis padding of the today/view-switch toolbar buttons. The inline axis reuses
     * `{spacing.md}` -- it matches on every preset's spacing scale. */
    toolbarButtonPaddingY: TokenValue;
    titleFontSize: TokenValue;
    cellMinHeight: TokenValue;
    cellMinHeightWeek: TokenValue;
    eventsGap: TokenValue;
    eventPaddingX: TokenValue;
    eventPaddingY: TokenValue;
    eventFontSize: TokenValue;
  };
  treeTable: {
    checkboxColumnWidth: TokenValue;
    toggleSize: TokenValue;
    toggleMarginEnd: TokenValue;
    toggleIconSize: TokenValue;
  };
  richTextEditor: {
    toolbarGap: TokenValue;
    toolSize: TokenValue;
    toolIconSize: TokenValue;
    /** `font-size` of an `<h1>` inside the editable content, in `em` relative to the editor's own
     * base font size. */
    contentHeadingFontSizeLg: TokenValue;
    /** `font-size` of an `<h2>` inside the editable content, in `em`. */
    contentHeadingFontSizeMd: TokenValue;
    /** Vertical margin shared by headings, paragraphs, and lists inside the editable content. */
    contentBlockSpacing: TokenValue;
    /** `padding-inline-start` of `<ul>`/`<ol>` inside the editable content, in `em`. */
    contentListIndent: TokenValue;
  };
  timeline: {
    markerIconSize: TokenValue;
    /** `min-width` of a connector segment when `orientation="horizontal"`; the vertical
     * orientation's connector length maps directly to `{spacing.lg}`. */
    connectorMinLength: TokenValue;
    contentGap: TokenValue;
  };
  cascadeSelect: {
    /** `min-width` of one cascade column's panel. Deliberately narrower than a top-level Select
     * dropdown, so it's its own token rather than reusing `select.*` like the rest of Cascade
     * Select does. */
    panelMinWidth: TokenValue;
  };
  contextMenu: {
    panelMinWidth: TokenValue;
  };
  autoComplete: {
    /** `padding-inline-end` reserved on the input so typed text never runs under the trailing
     * clear/loading affordance. */
    inputPaddingEnd: TokenValue;
  };
  progressBar: {
    trackHeight: Record<ButtonSize, TokenValue>;
    labelFontSize: TokenValue;
  };
  scrollTop: {
    buttonSize: TokenValue;
    iconSize: TokenValue;
  };
  splitButton: {
    menuMinWidth: TokenValue;
  };
  imageCropper: {
    /** Rule-of-thirds grid line color, drawn over the cropped image itself rather than over app
     * chrome -- conventionally a translucent white regardless of light/dark theme. */
    gridLineColor: TokenValue;
    zoomSliderMaxWidth: TokenValue;
  };
  organizationChart: {
    /** A node's box reuses `popover.*` for background/border/radius/shadow and the shared spacing
     * scale for its padding -- a node card is genuinely a popover-style surface. Only what's
     * actually new to this component gets its own token. */
    nodeMinWidth: TokenValue;
    nodeBackgroundSelected: TokenValue;
    nodeBorderSelected: TokenValue;
    toggleSize: TokenValue;
    /** Vertical connector length between a node and its children, and the horizontal gap between
     * sibling subtrees. */
    gap: TokenValue;
  };
  knob: {
    /** The track reuses `{muted}` and the arc reuses `{primary}` directly in CSS -- same precedent
     * as Progress Bar's track/fill. Only the sizing/label values are new to this component. */
    valueFontSize: TokenValue;
    labelColor: TokenValue;
    labelFontSize: TokenValue;
  };
  [component: string]: TokenTree;
};

// ---------------------------------------------------------------------------------------------
// Presets
// ---------------------------------------------------------------------------------------------

/** Recursively optional -- what an override layer (dark mode, `definePreset`) looks like. */
export type DeepPartial<T> = T extends TokenValue
  ? T
  : T extends object
    ? { [K in keyof T]?: DeepPartial<T[K]> }
    : T;

/**
 * A partial re-declaration of any token layer. Used for dark mode and for preset extension.
 *
 * Overriding `semantic` alone is normally enough for dark mode: component tokens reference
 * semantic tokens, so they follow automatically. `primitive` and `components` are here for the
 * cases where a mode genuinely needs a different raw value or a different component decision.
 */
export type ThemeOverrides = {
  primitive?: DeepPartial<PrimitiveTokens>;
  semantic?: DeepPartial<SemanticTokens>;
  components?: DeepPartial<ComponentTokens>;
};

/**
 * A complete theme. Presets are plain data: no CSS variable names, no dependency on the generator.
 *
 * Build one from scratch, or extend an existing one with `definePreset` -- see `define-preset.ts`.
 */
export interface ThemePreset {
  name: string;
  /** Layer 1: raw values. */
  primitive: PrimitiveTokens;
  /** Layer 2: meanings, referencing layer 1. Doubles as the light-mode values. */
  semantic: SemanticTokens;
  /** Layer 3: component decisions, referencing layer 2. */
  components: ComponentTokens;
  /** Dark-mode overrides, applied under the configured dark-mode selector. */
  dark?: ThemeOverrides;
  icons: IconTokens;
}

/** What `definePreset` accepts: any subset of a preset's layers. */
export type PresetOverrides = ThemeOverrides & {
  name?: string;
  dark?: ThemeOverrides;
  icons?: Partial<IconTokens>;
};
