import { IconTokens } from './icon-tokens';

/**
 * The SemiUI design-token type vocabulary.
 *
 * Tokens are authored in three layers, and each layer may only reference the layer(s) above it:
 *
 *     Primitive tokens   raw design values -- `blue.500`, `spacing.md`, `white`
 *           |
 *     Semantic tokens    what a value *means* -- `primary`, `destructive`, `mutedForeground`
 *           |
 *     Component tokens   what a component uses -- `button.variants.primary.background`
 *           |
 *     CSS variables      generated by the engine; preset authors never write these by hand
 *
 * A preset therefore describes design decisions, never CSS variable names. `{path}` references
 * (see `TokenValue`) are what connect the layers, and the engine turns each one into a live
 * `var()` reference at generation time -- see `buildThemeVars` in `token-engine.ts`.
 */

/**
 * A single token value. Always a string, and it can be any of:
 *
 * - a token reference -- `'{blue.500}'`, `'{primary}'`, `'{typography.fontSize.sm}'`
 * - a raw CSS value -- `'0.5rem'`, `'transparent'`, `'0 8px 24px rgb(15 23 42 / 0.10)'`
 * - a raw CSS value with references embedded in it --
 *   `'color-mix(in srgb, {primary} 15%, transparent)'`
 * - an explicit CSS variable reference -- `'var(--some-app-level-var)'`, for the rare case where
 *   a preset genuinely needs to point at something outside the token system
 *
 * Nothing about the type changes based on which form you pick; the engine tells them apart by
 * looking for `{...}` groups. Whole-object references (`'{blue}'` pointing at a full color scale)
 * are also supported wherever a subtree is expected -- see `PaletteTokens`.
 */
export type TokenValue = string;

/** An arbitrarily nested tree of token values. */
export type TokenTree = { [key: string]: TokenValue | TokenTree };

/** The 11 steps of a SemiUI color ramp -- 50 is the lightest tint, 950 the darkest shade. */
export type ColorShade = 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 950;

/**
 * An 11-step tint/shade ramp. 500 is conventionally the base color a scale is built around, so
 * `generateColorScale(base)[500] === base`.
 */
export type ColorScale = { [K in ColorShade]: TokenValue };

// ---------------------------------------------------------------------------------------------
// Layer 1 -- primitives
// ---------------------------------------------------------------------------------------------

/**
 * Raw design values, with no meaning attached. A primitive is never used directly by a component;
 * it exists so semantic tokens have something to point at, and so two semantic tokens that happen
 * to be the same color are the *same token* rather than two copies of one literal.
 *
 * Colors are usually authored as full `ColorScale` ramps (`blue`, `slate`, ...) plus a handful of
 * standalone constants (`white`, `black`, `transparent`), but the shape is deliberately open: any
 * nested tree of values works, and each leaf becomes referenceable by its own path.
 */
export type PrimitiveTokens = {
  white?: TokenValue;
  black?: TokenValue;
  transparent?: TokenValue;
  [name: string]: TokenValue | ColorScale | TokenTree | undefined;
};

// ---------------------------------------------------------------------------------------------
// Layer 2 -- semantics
// ---------------------------------------------------------------------------------------------

/**
 * The status vocabulary shared across Button/Tag/Badge and friends. `danger`/`error`/`warn` are
 * aliases -- they resolve to `destructive`/`destructive`/`warning` rather than carrying their own
 * color, so changing `destructive` changes all of them.
 */
export type SemanticColorTokens = {
  /** Page/surface background. */
  background: TokenValue;
  /** Default text color drawn on `background`. */
  foreground: TokenValue;

  primary: TokenValue;
  primaryForeground: TokenValue;
  secondary: TokenValue;
  secondaryForeground: TokenValue;
  success: TokenValue;
  successForeground: TokenValue;
  info: TokenValue;
  infoForeground: TokenValue;
  warning: TokenValue;
  warningForeground: TokenValue;
  destructive: TokenValue;
  destructiveForeground: TokenValue;
  help: TokenValue;
  helpForeground: TokenValue;
  /** Maximum-contrast ink against the current surface -- inverts between light and dark mode. */
  contrast: TokenValue;
  contrastForeground: TokenValue;

  /** A recessive surface: input fills, striped rows, disabled backgrounds. */
  muted: TokenValue;
  /** Readable ink designed to pair with `muted` -- secondary/placeholder text. */
  mutedForeground: TokenValue;
  border: TokenValue;
  /** Focus-ring color. Normally an alias of `primary`. */
  ring: TokenValue;

  /** Alias of `destructive`, for PrimeNG-style naming. */
  danger: TokenValue;
  dangerForeground: TokenValue;
  /** Alias of `destructive`, for the Toast/validation vocabulary. */
  error: TokenValue;
  errorForeground: TokenValue;
  /** Alias of `warning`, for PrimeNG-style naming. */
  warn: TokenValue;
  warnForeground: TokenValue;
};

/**
 * Full ramps backing the semantic colors. Usually a whole-object reference into a primitive scale
 * (`primary: '{blue}'`), which expands shade-by-shade, but individual shades can be authored or
 * overridden too. These are what the Tailwind bridge exposes as `primary-50` .. `primary-950`.
 */
export type PaletteTokens = { [scale: string]: TokenValue | Partial<ColorScale> };

export type SpacingTokens = {
  xs: TokenValue;
  sm: TokenValue;
  md: TokenValue;
  lg: TokenValue;
  xl: TokenValue;
};

export type RadiusTokens = {
  sm: TokenValue;
  md: TokenValue;
  lg: TokenValue;
  full: TokenValue;
};

export type TypographyTokens = {
  fontFamily: TokenValue;
  fontSize: { sm: TokenValue; md: TokenValue } & { [step: string]: TokenValue };
  /**
   * The named weights components draw from. `medium` is the workhorse (labels, buttons, table
   * headers); `semibold` and `bold` exist because components genuinely need them -- a stepper
   * circle, a calendar title, an editor heading -- and a hardcoded 600 or 700 in a component's
   * CSS is a weight no preset can ever restyle.
   *
   * Extra steps are allowed by the index signature. The four named ones are required so that a
   * component referencing `{typography.fontWeight.semibold}` can never resolve to nothing in a
   * hand-written preset.
   */
  fontWeight: {
    normal: TokenValue;
    medium: TokenValue;
    semibold: TokenValue;
    bold: TokenValue;
  } & { [step: string]: TokenValue };
};

/**
 * Opacities that carry a *state* meaning rather than a visual one. Only `disabled` today, and it
 * is what every component's own `opacityDisabled` points at by default, so one edit dims the whole
 * library consistently.
 *
 * Authored as a percentage rather than a bare number so overriding it reads unambiguously:
 * `opacity: 60` clamps to a fully opaque 1, `opacity: 60%` means what it says.
 */
export type OpacityTokens = {
  /**
   * How much a disabled component is dimmed. `'100%'` turns dimming off entirely, for a design
   * system that expresses "disabled" purely through the `*Disabled` colors instead.
   */
  disabled: TokenValue;
} & { [state: string]: TokenValue };

/**
 * What values *mean*. Colors sit flat at the top level (`primary`, `border`, ...); the non-color
 * scales live in their own named groups so they read -- and generate -- as their own namespaces.
 *
 * Every value here should reference a primitive rather than repeat a literal, so that changing one
 * primitive changes everything downstream of it.
 */
export type SemanticTokens = SemanticColorTokens & {
  palette: PaletteTokens;
  spacing: SpacingTokens;
  radius: RadiusTokens;
  typography: TypographyTokens;
  opacity: OpacityTokens;
};

// ---------------------------------------------------------------------------------------------
// Layer 3 -- components
// ---------------------------------------------------------------------------------------------

/**
 * The disabled state is expressed through two independent levers, and every component that has a
 * disabled state exposes both so an app can pick either -- or both:
 *
 * - **colors** -- `*Disabled` surface tokens (`backgroundDisabled`, `foregroundDisabled`,
 *   `borderDisabled`, ...). Point them at flat neutrals (`{muted}`/`{mutedForeground}`) for the
 *   "greyed out" look, or back at the component's *own* live colors so the component keeps its
 *   identity and only the opacity below dims it.
 * - **opacity** -- `opacityDisabled`, defaulting to the shared `{opacity.disabled}`. Set it to
 *   `'100%'` to switch dimming off and let the colors do all the work.
 *
 * Semi picks the second one everywhere: every `*Disabled` color points back at that component's
 * own live color, and `{opacity.disabled}` does all the fading -- so a disabled Destructive button
 * still reads as red, a disabled checked checkbox still reads as checked, and "unavailable" looks
 * the same across the library. A preset that wants the flat-grey look says so explicitly.
 *
 * A component whose disabled rule was a hardcoded `opacity: 0.4` before had no lever at all --
 * that is what this vocabulary replaces.
 */
export type ButtonSize = 'sm' | 'md' | 'lg';
export type AvatarSize = 'sm' | 'md' | 'lg' | 'xl';
export type DialogSize = 'sm' | 'md' | 'lg' | 'full';

/** Shared status vocabulary across Button/Tag/Badge, on top of each component's own style-only
 * variants (outline/ghost/link for Button, default/outline for Tag/Badge). */
export type Severity = 'primary' | 'secondary' | 'success' | 'info' | 'warn' | 'help' | 'danger' | 'contrast';
export type ButtonVariant = Severity | 'destructive' | 'link';
export type TagVariant = Severity | 'default' | 'destructive' | 'outline';
export type ToastVariant = 'default' | 'success' | 'error' | 'warning' | 'info';

export type SurfaceVariantTokens = {
  background: TokenValue;
  foreground: TokenValue;
  border: TokenValue;
};

export type ToastVariantTokens = SurfaceVariantTokens & {
  iconColor: TokenValue;
};

/**
 * Toast's variants, split because the neutral one genuinely has no icon: `variantIcon()` returns a
 * status glyph for success/error/warning/info and `null` for `default`, so an `iconColor` there
 * would be a colour with nothing to paint -- config that reads as available and silently does
 * nothing. Give Toast a `toastDefault` icon and this becomes a plain `Record` again.
 */
export type ToastVariantsTokens = Record<Exclude<ToastVariant, 'default'>, ToastVariantTokens> & {
  default: SurfaceVariantTokens;
};

/**
 * A button variant's own disabled palette, on top of the three surface colors it uses at rest.
 *
 * These exist per variant rather than once on `ButtonTokens` so a disabled button keeps its
 * variant's identity instead of every variant collapsing into the same flat grey slab. Semi points
 * each one back at the variant's *own* live color (`backgroundDisabled:
 * '{components.button.variants.primary.background}'`) and dims the whole button with
 * `opacityDisabled` -- so a preset that only recolors `background` gets a matching disabled state
 * for free, and a preset that genuinely wants a flat grey disabled state says so explicitly.
 *
 * The outlined and text modifiers have no fill of their own, so `backgroundDisabled` is ignored
 * for them (their background stays transparent); they use `borderDisabled` and `opacityDisabled`,
 * and take their ink from the variant's accent color.
 */
export type ButtonVariantTokens = SurfaceVariantTokens & {
  backgroundDisabled: TokenValue;
  foregroundDisabled: TokenValue;
  borderDisabled: TokenValue;
  /** Any CSS opacity value -- `'60%'` or `'0.6'`. Applied to the button as a whole. */
  opacityDisabled: TokenValue;
};

export type ButtonTokens = {
  radius: TokenValue;
  fontWeight: TokenValue;
  focusRing: TokenValue;
  /**
   * The disabled palette for a button with no variant of its own -- and the value Split Button,
   * Toggle Button and Toggle Group read, none of which are variant-aware. A variant's own
   * `variants.*.backgroundDisabled` (etc.) wins over these for `<s-button>`.
   */
  backgroundDisabled: TokenValue;
  foregroundDisabled: TokenValue;
  borderDisabled: TokenValue;
  opacityDisabled: TokenValue;
  paddingX: Record<ButtonSize, TokenValue>;
  paddingY: Record<ButtonSize, TokenValue>;
  fontSize: Record<ButtonSize, TokenValue>;
  variants: Record<ButtonVariant, ButtonVariantTokens>;
};

/** Input and Select share this field set; Select adds its own panel/option tokens on top. */
export type FieldTokens = {
  paddingX: TokenValue;
  paddingY: TokenValue;
  radius: TokenValue;
  fontSize: TokenValue;
  background: TokenValue;
  foreground: TokenValue;
  placeholderForeground: TokenValue;
  border: TokenValue;
  borderHover: TokenValue;
  borderFocus: TokenValue;
  focusRing: TokenValue;
  borderInvalid: TokenValue;
  backgroundDisabled: TokenValue;
  foregroundDisabled: TokenValue;
  /** Defaults to the same value as `border`, so a disabled field keeps its outline until a preset
   * says otherwise. */
  borderDisabled: TokenValue;
  /** Follows `{opacity.disabled}` in Semi. See the disabled-state note above `ButtonSize`. */
  opacityDisabled: TokenValue;
};

export type SelectTokens = FieldTokens & {
  panelBackground: TokenValue;
  panelBorder: TokenValue;
  panelShadow: TokenValue;
  /** Shared by Cascade Select's and Auto Complete's panels (both reuse `select.*` throughout):
   * the option list's `max-height` before it scrolls. */
  panelMaxHeight: TokenValue;
  optionForeground: TokenValue;
  optionBackgroundHover: TokenValue;
  optionBackgroundSelected: TokenValue;
  optionForegroundSelected: TokenValue;
};

/**
 * Per-component tokens. A component token exists for one of two reasons: it points a component at
 * a semantic decision (`background: '{primary}'`), or it carries a value that is genuinely local
 * to that component and has no design-system meaning (`dialog.widths.md`). Both are legitimate --
 * see the SemiUI theming docs. What a component token should *not* be is a duplicated copy of a
 * semantic value.
 *
 * The index signature at the end lets a preset add tokens for components SemiUI doesn't ship.
 */
export type ComponentTokens = {
  button: ButtonTokens;
  input: FieldTokens;
  select: SelectTokens;
  switch: {
    trackPadding: TokenValue;
    /** Opacity of a disabled switch, on top of `backgroundDisabled`. Any CSS opacity value. */
    opacityDisabled: TokenValue;
    trackBorderWidth: TokenValue;
    radius: TokenValue;
    background: TokenValue;
    backgroundChecked: TokenValue;
    border: TokenValue;
    borderChecked: TokenValue;
    thumbBackground: TokenValue;
    focusRing: TokenValue;
    backgroundDisabled: TokenValue;
    transitionDuration: TokenValue;
    trackWidth: Record<ButtonSize, TokenValue>;
    trackHeight: Record<ButtonSize, TokenValue>;
    thumbSize: Record<ButtonSize, TokenValue>;
  };
  checkbox: {
    radius: TokenValue;
    border: TokenValue;
    borderChecked: TokenValue;
    background: TokenValue;
    backgroundChecked: TokenValue;
    foregroundChecked: TokenValue;
    focusRing: TokenValue;
    backgroundDisabled: TokenValue;
    borderDisabled: TokenValue;
    opacityDisabled: TokenValue;
    size: Record<ButtonSize, TokenValue>;
  };
  radio: {
    border: TokenValue;
    borderChecked: TokenValue;
    background: TokenValue;
    backgroundDisabled: TokenValue;
    borderDisabled: TokenValue;
    opacityDisabled: TokenValue;
    dotBackground: TokenValue;
    focusRing: TokenValue;
    size: Record<ButtonSize, TokenValue>;
  };
  popover: {
    background: TokenValue;
    border: TokenValue;
    shadow: TokenValue;
    radius: TokenValue;
    foreground: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
  };
  tooltip: {
    background: TokenValue;
    foreground: TokenValue;
    radius: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
    fontSize: TokenValue;
  };
  skeleton: {
    background: TokenValue;
    shimmer: TokenValue;
    radius: TokenValue;
  };
  avatar: {
    background: TokenValue;
    foreground: TokenValue;
    radius: TokenValue;
    statusOnline: TokenValue;
    statusAway: TokenValue;
    statusBusy: TokenValue;
    statusOffline: TokenValue;
    /** Weight of the initials shown when there's no image. */
    fontWeight: TokenValue;
    size: Record<AvatarSize, TokenValue>;
    fontSize: Record<AvatarSize, TokenValue>;
  };
  tag: {
    radius: TokenValue;
    fontSize: TokenValue;
    fontWeight: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
    variants: Record<TagVariant, SurfaceVariantTokens>;
  };
  breadcrumb: {
    foreground: TokenValue;
    currentForeground: TokenValue;
    separatorColor: TokenValue;
    fontSize: TokenValue;
    /** Weight of the trailing "you are here" item, which is what distinguishes it from the
     * links before it alongside `currentForeground`. */
    currentFontWeight: TokenValue;
    gap: TokenValue;
  };
  badge: {
    size: TokenValue;
    dotSize: TokenValue;
    fontSize: TokenValue;
    fontWeight: TokenValue;
    ringColor: TokenValue;
    variants: Record<TagVariant, SurfaceVariantTokens>;
  };
  pagination: {
    radius: TokenValue;
    gap: TokenValue;
    size: TokenValue;
    border: TokenValue;
    background: TokenValue;
    foreground: TokenValue;
    backgroundHover: TokenValue;
    backgroundActive: TokenValue;
    foregroundActive: TokenValue;
    backgroundDisabled: TokenValue;
    foregroundDisabled: TokenValue;
    opacityDisabled: TokenValue;
  };
  rating: {
    filledColor: TokenValue;
    emptyColor: TokenValue;
    /** Star colors for a disabled Rating. Default back to the live `filledColor`/`emptyColor`, so
     * out of the box a disabled Rating is the same stars dimmed by `opacityDisabled`. */
    filledColorDisabled: TokenValue;
    emptyColorDisabled: TokenValue;
    opacityDisabled: TokenValue;
    gap: TokenValue;
    size: Record<ButtonSize, TokenValue>;
  };
  accordion: {
    border: TokenValue;
    radius: TokenValue;
    headerBackground: TokenValue;
    headerBackgroundHover: TokenValue;
    headerForeground: TokenValue;
    headerBackgroundDisabled: TokenValue;
    headerForegroundDisabled: TokenValue;
    opacityDisabled: TokenValue;
    panelBackground: TokenValue;
    panelForeground: TokenValue;
    fontSize: TokenValue;
    fontWeight: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
  };
  tabs: {
    border: TokenValue;
    gap: TokenValue;
    foreground: TokenValue;
    foregroundActive: TokenValue;
    backgroundDisabled: TokenValue;
    foregroundDisabled: TokenValue;
    opacityDisabled: TokenValue;
    indicatorColor: TokenValue;
    indicatorThickness: TokenValue;
    fontSize: TokenValue;
    fontWeight: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
  };
  stepper: {
    circleSize: TokenValue;
    circleBorder: TokenValue;
    circleBackground: TokenValue;
    circleForeground: TokenValue;
    circleBackgroundActive: TokenValue;
    circleForegroundActive: TokenValue;
    circleBackgroundCompleted: TokenValue;
    circleForegroundCompleted: TokenValue;
    connectorColor: TokenValue;
    connectorColorCompleted: TokenValue;
    labelColor: TokenValue;
    labelColorActive: TokenValue;
    descriptionColor: TokenValue;
    fontSize: TokenValue;
    /** Weight of the number inside a step's circle. */
    circleFontWeight: TokenValue;
    /** Weight of a step's label. */
    labelFontWeight: TokenValue;
    /** A disabled step dims as a whole -- circle, connector, label and description together. The
     * recolor lever for one of those parts is that part's own token above. */
    opacityDisabled: TokenValue;
    gap: TokenValue;
  };
  slider: {
    trackSize: TokenValue;
    trackColor: TokenValue;
    fillColor: TokenValue;
    thumbSize: TokenValue;
    thumbBackground: TokenValue;
    thumbBorder: TokenValue;
    thumbBorderFocus: TokenValue;
    tickColor: TokenValue;
    tickSize: TokenValue;
    bubbleBackground: TokenValue;
    bubbleForeground: TokenValue;
    /** Track colors for a disabled Slider. Default back to the live `trackColor`/`fillColor`. */
    trackColorDisabled: TokenValue;
    fillColorDisabled: TokenValue;
    opacityDisabled: TokenValue;
  };
  chart: {
    gridColor: TokenValue;
    axisLabelColor: TokenValue;
    axisLabelFontSize: TokenValue;
    tooltipBackground: TokenValue;
    tooltipForeground: TokenValue;
    tooltipRadius: TokenValue;
    legendFontSize: TokenValue;
    legendGap: TokenValue;
    lineStrokeWidth: TokenValue;
    areaOpacity: TokenValue;
  };
  table: {
    border: TokenValue;
    radius: TokenValue;
    headerBackground: TokenValue;
    headerForeground: TokenValue;
    /**
     * A body row's own fill, underneath the three state layers below. Transparent by default, so
     * rows show whatever surface the table sits on; point it at `{background}` for opaque rows
     * (which also makes a striped table's odd rows read as a deliberate stripe rather than as the
     * surface showing through).
     */
    rowBackground: TokenValue;
    rowBackgroundStriped: TokenValue;
    rowBackgroundHover: TokenValue;
    rowBackgroundSelected: TokenValue;
    /** Body cell text color. Header cells use `headerForeground`. */
    rowForeground: TokenValue;
    fontSize: TokenValue;
    /** Weight of a header cell. Tree Table reads this too -- its header is the same header. */
    headerFontWeight: TokenValue;
    cellPaddingX: TokenValue;
    cellPaddingY: TokenValue;
    sortIconColor: TokenValue;
    sortIconColorActive: TokenValue;
    sortIconSize: TokenValue;
    /** Width of the leading selection column, when `selectionMode` renders one. */
    checkboxColumnWidth: TokenValue;
    /** How wide the toolbar's filter field is allowed to grow. */
    filterMaxWidth: TokenValue;
    /** Width of the footer's rows-per-page Select. */
    rowsPerPageWidth: TokenValue;
  };
  colorPicker: {
    svAreaSize: TokenValue;
    hueTrackHeight: TokenValue;
    thumbSize: TokenValue;
    hueThumbWidth: TokenValue;
    presetSize: TokenValue;
    presetGap: TokenValue;
    presetBorder: TokenValue;
    presetBorderSelected: TokenValue;
  };
  datePicker: {
    daySize: TokenValue;
    fontSize: TokenValue;
    dayForeground: TokenValue;
    dayForegroundOutsideMonth: TokenValue;
    dayBackgroundHover: TokenValue;
    dayBackgroundSelected: TokenValue;
    dayForegroundSelected: TokenValue;
    dayBorderToday: TokenValue;
    /** A day -- or a month/year cell -- that `min`/`max`/`disabledDates` rules out. */
    dayBackgroundDisabled: TokenValue;
    dayForegroundDisabled: TokenValue;
    dayOpacityDisabled: TokenValue;
    navBackgroundHover: TokenValue;
    weekdayForeground: TokenValue;
    monthLabelForeground: TokenValue;
    /** Weight of the panel's own chrome -- the month/year buttons and the time separator -- as
     * opposed to the day numbers in the grid, which stay at the inherited weight. */
    labelFontWeight: TokenValue;
  };
  carousel: {
    radius: TokenValue;
    arrowSize: TokenValue;
    arrowBackground: TokenValue;
    arrowBackgroundHover: TokenValue;
    arrowColor: TokenValue;
    arrowBackgroundDisabled: TokenValue;
    arrowColorDisabled: TokenValue;
    arrowOpacityDisabled: TokenValue;
    dotSize: TokenValue;
    dotColor: TokenValue;
    dotColorActive: TokenValue;
    dotGap: TokenValue;
  };
  toast: {
    radius: TokenValue;
    shadow: TokenValue;
    paddingX: TokenValue;
    paddingY: TokenValue;
    gap: TokenValue;
    /** Every toast's width, e.g. `'24rem'`. */
    width: TokenValue;
    titleFontWeight: TokenValue;
    /** `backdrop-filter` value applied to every toast, e.g. `'blur(12px)'`. `'none'` disables it.
     * Pairs with translucent variant backgrounds (see `variants.*.background`). */
    blur: TokenValue;
    variants: ToastVariantsTokens;
  };
  fileUpload: {
    border: TokenValue;
    borderDragOver: TokenValue;
    background: TokenValue;
    backgroundDragOver: TokenValue;
    radius: TokenValue;
    iconColor: TokenValue;
    hintColor: TokenValue;
    acceptColor: TokenValue;
    itemBackground: TokenValue;
    itemBorder: TokenValue;
    itemRadius: TokenValue;
    thumbSize: TokenValue;
    rejectionColor: TokenValue;
    backgroundDisabled: TokenValue;
    borderDisabled: TokenValue;
    opacityDisabled: TokenValue;
  };
  dialog: {
    backdropColor: TokenValue;
    panelBackground: TokenValue;
    panelBorder: TokenValue;
    radius: TokenValue;
    shadow: TokenValue;
    headerBorder: TokenValue;
    footerBorder: TokenValue;
    titleFontSize: TokenValue;
    titleFontWeight: TokenValue;
    padding: TokenValue;
    widths: Record<DialogSize, TokenValue>;
  };
  speedDial: {
    /** Radius of the trigger and of every mini action. `'{radius.full}'` gives the conventional
     * circular FAB; a square-cornered preset sets its own. */
    radius: TokenValue;
    /** Elevation on the trigger and on every mini action. `'none'` for presets that don't use
     * shadow. */
    shadow: TokenValue;
    /** Distance between the trigger and the fan of actions, and between the actions themselves. */
    gap: TokenValue;
    /** Diameter of one mini action, per the Speed Dial's `size`. Kept below the trigger's own size
     * so the FAB stays visually dominant. */
    actionSize: Record<ButtonSize, TokenValue>;
    actionBackground: TokenValue;
    actionForeground: TokenValue;
    actionBorder: TokenValue;
    actionBackgroundDisabled: TokenValue;
    actionForegroundDisabled: TokenValue;
    actionOpacityDisabled: TokenValue;
    /** Delay step between consecutive actions in the staggered reveal, e.g. `'40ms'` -- the nth
     * action waits n times this. `'0ms'` reveals them all at once. */
    stagger: TokenValue;
  };
  fullCalendar: {
    navButtonSize: TokenValue;
    navIconSize: TokenValue;
    /** Block-axis padding of the today/view-switch toolbar buttons. The inline axis reuses
     * `{spacing.md}` -- it matches on every preset's spacing scale. */
    toolbarButtonPaddingY: TokenValue;
    titleFontSize: TokenValue;
    titleFontWeight: TokenValue;
    /** Weight of the Mon/Tue/... column headings. */
    weekdayFontWeight: TokenValue;
    /** Weight of today's date number, which is what makes it read as today alongside its fill. */
    todayFontWeight: TokenValue;
    cellMinHeight: TokenValue;
    cellMinHeightWeek: TokenValue;
    eventsGap: TokenValue;
    eventPaddingX: TokenValue;
    eventPaddingY: TokenValue;
    eventFontSize: TokenValue;
  };
  treeTable: {
    checkboxColumnWidth: TokenValue;
    toggleSize: TokenValue;
    toggleMarginEnd: TokenValue;
    toggleIconSize: TokenValue;
  };
  richTextEditor: {
    toolbarGap: TokenValue;
    toolSize: TokenValue;
    toolIconSize: TokenValue;
    /** A toolbar button that doesn't apply to the current selection. The editable area itself is
     * a field and takes `input.*Disabled` like every other one. */
    toolBackgroundDisabled: TokenValue;
    toolForegroundDisabled: TokenValue;
    toolOpacityDisabled: TokenValue;
    /** `font-size` of an `<h1>` inside the editable content, in `em` relative to the editor's own
     * base font size. */
    contentHeadingFontSizeLg: TokenValue;
    /** `font-size` of an `<h2>` inside the editable content, in `em`. */
    contentHeadingFontSizeMd: TokenValue;
    /** Weight shared by `<h1>` and `<h2>` inside the editable content. */
    contentHeadingFontWeight: TokenValue;
    /** Vertical margin shared by headings, paragraphs, and lists inside the editable content. */
    contentBlockSpacing: TokenValue;
    /** `padding-inline-start` of `<ul>`/`<ol>` inside the editable content, in `em`. */
    contentListIndent: TokenValue;
  };
  timeline: {
    markerIconSize: TokenValue;
    /** `min-width` of a connector segment when `orientation="horizontal"`; the vertical
     * orientation's connector length maps directly to `{spacing.lg}`. */
    connectorMinLength: TokenValue;
    contentGap: TokenValue;
    /** Weight of an entry's title. Timeline reuses `stepper.*` for its font size and label
     * colors -- an entry genuinely is a step -- but Stepper has no title of its own. */
    titleFontWeight: TokenValue;
  };
  cascadeSelect: {
    /** `min-width` of one cascade column's panel. Deliberately narrower than a top-level Select
     * dropdown, so it's its own token rather than reusing `select.*` like the rest of Cascade
     * Select does. */
    panelMinWidth: TokenValue;
  };
  contextMenu: {
    panelMinWidth: TokenValue;
    /** A menu item marked `disabled`. The rest of an item's colors come from `select.option*`,
     * which is what a menu item genuinely is. */
    itemBackgroundDisabled: TokenValue;
    itemForegroundDisabled: TokenValue;
    itemOpacityDisabled: TokenValue;
  };
  autoComplete: {
    /** `padding-inline-end` reserved on the input so typed text never runs under the trailing
     * clear/loading affordance. */
    inputPaddingEnd: TokenValue;
  };
  progressBar: {
    trackHeight: Record<ButtonSize, TokenValue>;
    labelFontSize: TokenValue;
  };
  scrollTop: {
    buttonSize: TokenValue;
    iconSize: TokenValue;
  };
  splitButton: {
    menuMinWidth: TokenValue;
  };
  /**
   * A segmented control is a *track* holding *segments*, and the two have to be styleable
   * independently -- which is exactly what reusing `button.*` throughout could not express.
   *
   * The colors are still Button's: a Toggle Group's "primary" genuinely is Button's primary, and
   * copying `variants.*` here would be the duplicated-semantic-value this file warns about. What
   * lives here is the chrome and geometry that make the thing a group rather than a row of
   * buttons, plus the handful of shared decisions (padding, font, focus ring) a preset needs to
   * be able to move for the group *without* moving them for every Button on the page.
   *
   * Semi's defaults reproduce the joined-buttons look exactly -- a track with no fill, border or
   * padding, over segments sharing a collapsed 1px border with only the group's outer corners
   * rounded. Repointing six of them gives the padded-track style instead: a filled, bordered
   * track with a gap between individually rounded, borderless segments.
   */
  toggleGroup: {
    // --- the track -----------------------------------------------------------------------------
    background: TokenValue;
    /** Only visible once `borderWidth` is non-zero, which is why the two are separate: a preset
     * turning the track on sets the width and inherits a sensible color. */
    border: TokenValue;
    borderWidth: TokenValue;
    radius: TokenValue;
    padding: TokenValue;
    /** Space between segments. Non-zero is what separates them into individual pills; it also
     * cancels the shared-border collapse, since segments that don't touch have no seam to merge. */
    gap: TokenValue;

    // --- the segments --------------------------------------------------------------------------
    itemBackground: TokenValue;
    itemBorderWidth: TokenValue;
    /** Every segment's corners. `0` in the joined default, so only the group's two outer corners
     * (below) are rounded. */
    itemRadius: TokenValue;
    /** The first and last segment's *outer* corners -- the ends of the group. Kept separate from
     * `itemRadius` so the joined default can round the group's ends without rounding the shared
     * inner seams; set both to the same value for uniformly rounded segments. */
    itemRadiusOuter: TokenValue;
    /** Space between a segment's icon and its label. */
    itemGap: TokenValue;
    itemPaddingX: Record<ButtonSize, TokenValue>;
    itemPaddingY: Record<ButtonSize, TokenValue>;
    itemFontSize: Record<ButtonSize, TokenValue>;
    fontWeight: TokenValue;
    focusRing: TokenValue;
    opacityDisabled: TokenValue;
  };
  imageCropper: {
    /** Rule-of-thirds grid line color, drawn over the cropped image itself rather than over app
     * chrome -- conventionally a translucent white regardless of light/dark theme. */
    gridLineColor: TokenValue;
    zoomSliderMaxWidth: TokenValue;
  };
  organizationChart: {
    /** A node's box reuses `popover.*` for background/border/radius/shadow and the shared spacing
     * scale for its padding -- a node card is genuinely a popover-style surface. Only what's
     * actually new to this component gets its own token. */
    nodeMinWidth: TokenValue;
    nodeBackgroundSelected: TokenValue;
    nodeBorderSelected: TokenValue;
    toggleSize: TokenValue;
    /** Vertical connector length between a node and its children, and the horizontal gap between
     * sibling subtrees. */
    gap: TokenValue;
  };
  knob: {
    /** The track reuses `{muted}` and the arc reuses `{primary}` directly in CSS -- same precedent
     * as Progress Bar's track/fill. Only the sizing/label values are new to this component. */
    valueFontSize: TokenValue;
    valueFontWeight: TokenValue;
    labelColor: TokenValue;
    labelFontSize: TokenValue;
  };
  [component: string]: TokenTree;
};

// ---------------------------------------------------------------------------------------------
// Presets
// ---------------------------------------------------------------------------------------------

/** Recursively optional -- what an override layer (dark mode, `definePreset`) looks like. */
export type DeepPartial<T> = T extends TokenValue
  ? T
  : T extends object
    ? { [K in keyof T]?: DeepPartial<T[K]> }
    : T;

/**
 * A partial re-declaration of any token layer. Used for dark mode and for preset extension.
 *
 * Overriding `semantic` alone is normally enough for dark mode: component tokens reference
 * semantic tokens, so they follow automatically. `primitive` and `components` are here for the
 * cases where a mode genuinely needs a different raw value or a different component decision.
 */
export type ThemeOverrides = {
  primitive?: DeepPartial<PrimitiveTokens>;
  semantic?: DeepPartial<SemanticTokens>;
  components?: DeepPartial<ComponentTokens>;
};

/**
 * A complete theme. Presets are plain data: no CSS variable names, no dependency on the generator.
 *
 * Build one from scratch, or extend an existing one with `definePreset` -- see `define-preset.ts`.
 */
export interface ThemePreset {
  name: string;
  /** Layer 1: raw values. */
  primitive: PrimitiveTokens;
  /** Layer 2: meanings, referencing layer 1. Doubles as the light-mode values. */
  semantic: SemanticTokens;
  /** Layer 3: component decisions, referencing layer 2. */
  components: ComponentTokens;
  /** Dark-mode overrides, applied under the configured dark-mode selector. */
  dark?: ThemeOverrides;
  icons: IconTokens;
}

/** What `definePreset` accepts: any subset of a preset's layers. */
export type PresetOverrides = ThemeOverrides & {
  name?: string;
  dark?: ThemeOverrides;
  icons?: Partial<IconTokens>;
};
