import { ColorTokens, ThemePreset } from '@semiui/tokens';

/** IBM Carbon's signature move: almost no radius, almost no shadow. Menus/dropdowns lean on a
 * 1px border for separation instead of elevation -- Carbon deliberately avoids the "floating
 * card" look most design systems (including this library's other presets) default to. */
const NO_SHADOW = 'none';
const dialogShadow = '0 4px 8px rgb(0 0 0 / 0.16), 0 1px 3px rgb(0 0 0 / 0.2)';

/** IBM's actual documented palette (Gray 100 / Blue 60 / Red 60) -- #0f62fe and #161616 are as
 * recognizably "Carbon" as a hex code gets to anyone who's used an IBM product. */
const lightColor: ColorTokens = {
  background: '#ffffff',
  foreground: '#161616',
  primary: '#0f62fe',
  primaryForeground: '#ffffff',
  destructive: '#da1e28',
  destructiveForeground: '#ffffff',
  border: '#e0e0e0',
  ring: '#0f62fe',
  muted: '#f4f4f4',
  mutedForeground: '#525252',
};

const darkColor: ColorTokens = {
  background: '#161616',
  foreground: '#f4f4f4',
  primary: '#4589ff',
  primaryForeground: '#ffffff',
  destructive: '#fa4d56',
  destructiveForeground: '#ffffff',
  border: '#393939',
  ring: '#4589ff',
  muted: '#262626',
  mutedForeground: '#c6c6c6',
};

export const Carbon: ThemePreset = {
  name: 'carbon',
  tokens: {
    color: lightColor,
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
      xl: '1.5rem',
    },
    // Zero radius everywhere except things that are genuinely circular (avatars, the switch
    // pill) -- Carbon's rectangles stay rectangles, on purpose.
    radius: {
      sm: '0',
      md: '0',
      lg: '0',
      full: '9999px',
    },
    typography: {
      fontFamily: '"IBM Plex Sans", sans-serif',
      fontSizeSm: '0.875rem',
      fontSizeMd: '1rem',
      fontWeightMedium: '500',
    },
    comp: {
      button: {
        radius: '0',
        fontWeight: '500',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        paddingX: { sm: '1rem', md: '1rem', lg: '1.25rem' },
        paddingY: { sm: '0.5rem', md: '0.75rem', lg: '1rem' },
        fontSize: { sm: '0.8125rem', md: '0.875rem', lg: '1rem' },
        variants: {
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'var(--semiui-color-primary)',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-muted)',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          success: {
            background: '#24a148',
            foreground: '#ffffff',
            border: '#24a148',
          },
          info: {
            background: '#0043ce',
            foreground: '#ffffff',
            border: '#0043ce',
          },
          warn: {
            background: '#f1c21b',
            foreground: '#161616',
            border: '#f1c21b',
          },
          help: {
            background: '#8a3ffc',
            foreground: '#ffffff',
            border: '#8a3ffc',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'var(--semiui-color-foreground)',
          },
          link: {
            background: 'transparent',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
        },
      },
      input: {
        paddingX: '0.75rem',
        paddingY: '0.6875rem',
        radius: '0',
        fontSize: '0.875rem',
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'var(--semiui-color-border)',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      select: {
        paddingX: '0.75rem',
        paddingY: '0.6875rem',
        radius: '0',
        fontSize: '0.875rem',
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'var(--semiui-color-border)',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'var(--semiui-color-border)',
        panelShadow: NO_SHADOW,
        optionForeground: 'var(--semiui-color-foreground)',
        optionBackgroundHover: 'var(--semiui-color-muted)',
        optionBackgroundSelected: 'var(--semiui-color-primary)',
        optionForegroundSelected: 'var(--semiui-color-primary-foreground)',
      },
      switch: {
        trackPadding: '0.125rem',
        trackBorderWidth: '1px',
        radius: 'var(--semiui-radius-full)',
        background: 'var(--semiui-color-muted-foreground)',
        backgroundChecked: 'var(--semiui-color-primary)',
        border: 'var(--semiui-color-border)',
        borderChecked: 'var(--semiui-color-primary)',
        thumbBackground: 'var(--semiui-color-background)',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        transitionDuration: '0.15s',
        trackWidth: { sm: '2rem', md: '2.75rem', lg: '3.5rem' },
        trackHeight: { sm: '1.125rem', md: '1.5rem', lg: '1.875rem' },
        thumbSize: { sm: '0.875rem', md: '1.125rem', lg: '1.5rem' },
      },
      checkbox: {
        // A hair of rounding, not zero -- Carbon's actual checkbox shape, and a useful reminder
        // that "flat" doesn't mean "every single radius token is literally 0".
        radius: '0.0625rem',
        border: 'var(--semiui-color-muted-foreground)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundChecked: 'var(--semiui-color-primary)',
        foregroundChecked: 'var(--semiui-color-primary-foreground)',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      radio: {
        border: 'var(--semiui-color-muted-foreground)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        dotBackground: 'var(--semiui-color-primary)',
        focusRing: 'var(--semiui-color-ring)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      popover: {
        background: 'var(--semiui-color-background)',
        border: 'var(--semiui-color-border)',
        shadow: NO_SHADOW,
        radius: '0',
        foreground: 'var(--semiui-color-foreground)',
        paddingX: '1rem',
        paddingY: '0.75rem',
      },
      tooltip: {
        background: '#393939',
        foreground: '#ffffff',
        radius: '0',
        paddingX: '0.5rem',
        paddingY: '0.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
      },
      skeleton: {
        background: 'var(--semiui-color-muted)',
        shimmer: 'color-mix(in srgb, var(--semiui-color-muted-foreground) 20%, transparent)',
        radius: '0',
      },
      avatar: {
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        // The one deliberate exception to "everything is square" -- user photos read better
        // circular regardless of design system, and Carbon's own user-avatar pattern agrees.
        radius: 'var(--semiui-radius-full)',
        statusOnline: '#24a148',
        statusAway: '#f1c21b',
        statusBusy: '#da1e28',
        statusOffline: '#8d8d8d',
        size: { sm: '1.75rem', md: '2.5rem', lg: '3.5rem', xl: '5rem' },
        fontSize: { sm: '0.625rem', md: '0.875rem', lg: '1.125rem', xl: '1.5rem' },
      },
      tag: {
        // A small nod of rounding -- Carbon's real tag shape, distinct from the fully-square
        // buttons/inputs and the fully-round avatar.
        radius: '0.125rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        paddingX: '0.5rem',
        paddingY: '0.125rem',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'color-mix(in srgb, var(--semiui-color-primary) 15%, transparent)',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-muted-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          danger: {
            background: 'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          success: {
            background: 'color-mix(in srgb, #24a148 15%, transparent)',
            foreground: '#24a148',
            border: 'transparent',
          },
          info: {
            background: 'color-mix(in srgb, #0043ce 15%, transparent)',
            foreground: '#0043ce',
            border: 'transparent',
          },
          warn: {
            background: 'color-mix(in srgb, #f1c21b 20%, transparent)',
            foreground: '#795600',
            border: 'transparent',
          },
          help: {
            background: 'color-mix(in srgb, #8a3ffc 15%, transparent)',
            foreground: '#8a3ffc',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'transparent',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      breadcrumb: {
        foreground: 'var(--semiui-color-muted-foreground)',
        currentForeground: 'var(--semiui-color-foreground)',
        separatorColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: '0.375rem',
      },
      badge: {
        size: '1.25rem',
        dotSize: '0.625rem',
        fontSize: '0.6875rem',
        ringColor: 'var(--semiui-color-background)',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          success: {
            background: '#24a148',
            foreground: '#ffffff',
            border: 'transparent',
          },
          info: {
            background: '#0043ce',
            foreground: '#ffffff',
            border: 'transparent',
          },
          warn: {
            background: '#f1c21b',
            foreground: '#161616',
            border: 'transparent',
          },
          help: {
            background: '#8a3ffc',
            foreground: '#ffffff',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      pagination: {
        radius: '0',
        gap: '0',
        size: '2.5rem',
        border: 'var(--semiui-color-border)',
        background: 'transparent',
        foreground: 'var(--semiui-color-foreground)',
        backgroundHover: 'var(--semiui-color-muted)',
        backgroundActive: 'var(--semiui-color-primary)',
        foregroundActive: 'var(--semiui-color-primary-foreground)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      rating: {
        filledColor: '#f1c21b',
        emptyColor: 'var(--semiui-color-border)',
        gap: '0',
        size: { sm: '1.25rem', md: '2rem', lg: '2.75rem' },
      },
      accordion: {
        border: 'var(--semiui-color-border)',
        radius: '0',
        headerBackground: 'transparent',
        headerBackgroundHover: 'var(--semiui-color-muted)',
        headerForeground: 'var(--semiui-color-foreground)',
        panelBackground: 'transparent',
        panelForeground: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      tabs: {
        border: 'var(--semiui-color-border)',
        gap: 'var(--semiui-spacing-md)',
        foreground: 'var(--semiui-color-muted-foreground)',
        foregroundActive: 'var(--semiui-color-foreground)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        indicatorColor: 'var(--semiui-color-primary)',
        indicatorThickness: '2px',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      stepper: {
        circleSize: '2rem',
        circleBorder: 'var(--semiui-color-border)',
        circleBackground: 'var(--semiui-color-background)',
        circleForeground: 'var(--semiui-color-muted-foreground)',
        circleBackgroundActive: 'var(--semiui-color-primary)',
        circleForegroundActive: 'var(--semiui-color-primary-foreground)',
        circleBackgroundCompleted: 'var(--semiui-color-primary)',
        circleForegroundCompleted: 'var(--semiui-color-primary-foreground)',
        connectorColor: 'var(--semiui-color-border)',
        connectorColorCompleted: 'var(--semiui-color-primary)',
        labelColor: 'var(--semiui-color-muted-foreground)',
        labelColorActive: 'var(--semiui-color-foreground)',
        descriptionColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: 'var(--semiui-spacing-sm)',
      },
      slider: {
        trackSize: '0.25rem',
        trackColor: 'var(--semiui-color-border)',
        fillColor: 'var(--semiui-color-primary)',
        thumbSize: '1rem',
        thumbBackground: 'var(--semiui-color-primary)',
        thumbBorder: 'var(--semiui-color-primary)',
        thumbBorderFocus: 'var(--semiui-color-ring)',
        tickColor: 'var(--semiui-color-border)',
        tickSize: '0.25rem',
        bubbleBackground: 'var(--semiui-color-foreground)',
        bubbleForeground: 'var(--semiui-color-background)',
      },
      chart: {
        gridColor: 'var(--semiui-color-border)',
        axisLabelColor: 'var(--semiui-color-muted-foreground)',
        axisLabelFontSize: '9px',
        tooltipBackground: '#393939',
        tooltipForeground: '#ffffff',
        tooltipRadius: '0',
        legendFontSize: 'var(--semiui-typography-font-size-sm)',
        legendGap: 'var(--semiui-spacing-md)',
        lineStrokeWidth: '2',
        areaOpacity: '0.15',
      },
      table: {
        border: 'var(--semiui-color-border)',
        radius: '0',
        headerBackground: 'var(--semiui-color-muted)',
        headerForeground: 'var(--semiui-color-foreground)',
        rowBackground: 'var(--semiui-color-background)',
        rowBackgroundStriped: 'var(--semiui-color-muted)',
        rowBackgroundHover: 'var(--semiui-color-muted)',
        rowBackgroundSelected: 'color-mix(in srgb, var(--semiui-color-primary) 12%, transparent)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        cellPaddingX: 'var(--semiui-spacing-md)',
        cellPaddingY: 'var(--semiui-spacing-sm)',
        sortIconColor: 'var(--semiui-color-muted-foreground)',
        sortIconColorActive: 'var(--semiui-color-foreground)',
      },
      colorPicker: {
        svAreaSize: '12rem',
        hueTrackHeight: '0.75rem',
        thumbSize: '1rem',
        hueThumbWidth: '0.75rem',
        presetSize: '1.5rem',
        presetGap: '0.375rem',
        presetBorder: 'var(--semiui-color-border)',
        presetBorderSelected: 'var(--semiui-color-primary)',
      },
      datePicker: {
        daySize: '2.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        dayForeground: 'var(--semiui-color-foreground)',
        dayForegroundOutsideMonth: 'var(--semiui-color-muted-foreground)',
        dayBackgroundHover: 'var(--semiui-color-muted)',
        dayBackgroundSelected: 'var(--semiui-color-primary)',
        dayForegroundSelected: 'var(--semiui-color-primary-foreground)',
        dayBorderToday: 'var(--semiui-color-primary)',
        navBackgroundHover: 'var(--semiui-color-muted)',
        weekdayForeground: 'var(--semiui-color-muted-foreground)',
        monthLabelForeground: 'var(--semiui-color-foreground)',
      },
      carousel: {
        radius: '0',
        arrowSize: '2.5rem',
        arrowBackground: 'rgb(0 0 0 / 0.4)',
        arrowBackgroundHover: 'rgb(0 0 0 / 0.6)',
        arrowColor: '#fff',
        dotSize: '0.5rem',
        dotColor: 'var(--semiui-color-border)',
        dotColorActive: 'var(--semiui-color-primary)',
        dotGap: 'var(--semiui-spacing-xs)',
      },
      toast: {
        radius: '0',
        shadow: dialogShadow,
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
        gap: 'var(--semiui-spacing-sm)',
        width: '24rem',
        blur: 'none',
        variants: {
          default: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
            iconColor: 'var(--semiui-color-muted-foreground)',
          },
          success: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: '#24a148',
            iconColor: '#24a148',
          },
          error: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-destructive)',
            iconColor: 'var(--semiui-color-destructive)',
          },
          warning: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: '#f1c21b',
            iconColor: '#795600',
          },
          info: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: '#0043ce',
            iconColor: '#0043ce',
          },
        },
      },
      fileUpload: {
        border: 'var(--semiui-color-border)',
        borderDragOver: 'var(--semiui-color-primary)',
        background: 'transparent',
        backgroundDragOver: 'var(--semiui-color-muted)',
        radius: '0',
        iconColor: 'var(--semiui-color-muted-foreground)',
        hintColor: 'var(--semiui-color-foreground)',
        acceptColor: 'var(--semiui-color-muted-foreground)',
        itemBackground: 'var(--semiui-color-muted)',
        itemBorder: 'var(--semiui-color-border)',
        itemRadius: '0',
        thumbSize: '2.5rem',
        rejectionColor: 'var(--semiui-color-destructive)',
      },
      dialog: {
        backdropColor: 'rgb(0 0 0 / 0.5)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'var(--semiui-color-border)',
        radius: '0',
        shadow: dialogShadow,
        headerBorder: 'var(--semiui-color-border)',
        footerBorder: 'var(--semiui-color-border)',
        titleFontSize: '1.125rem',
        titleFontWeight: '600',
        padding: 'var(--semiui-spacing-lg)',
        widths: { sm: '24rem', md: '32rem', lg: '48rem', full: 'calc(100vw - 2rem)' },
      },
    },
  },
  darkColor,
  icons: {
    loading: { type: 'ng-icon', name: 'lucideLoaderCircle' },
    chevronDown: { type: 'ng-icon', name: 'lucideChevronDown' },
    clear: { type: 'ng-icon', name: 'lucideX' },
    passwordShow: { type: 'ng-icon', name: 'lucideEye' },
    passwordHide: { type: 'ng-icon', name: 'lucideEyeOff' },
    checkboxCheck: { type: 'ng-icon', name: 'lucideCheck' },
    checkboxIndeterminate: { type: 'ng-icon', name: 'lucideMinus' },
    search: { type: 'ng-icon', name: 'lucideSearch' },
    plus: { type: 'ng-icon', name: 'lucidePlus' },
    minus: { type: 'ng-icon', name: 'lucideMinus' },
    avatarFallback: { type: 'ng-icon', name: 'lucideUser' },
    rating: { type: 'ng-icon', name: 'lucideStar' },
    upload: { type: 'ng-icon', name: 'lucideUpload' },
    file: { type: 'ng-icon', name: 'lucideFile' },
    toastSuccess: { type: 'ng-icon', name: 'lucideCircleCheck' },
    toastError: { type: 'ng-icon', name: 'lucideCircleX' },
    toastWarning: { type: 'ng-icon', name: 'lucideTriangleAlert' },
    toastInfo: { type: 'ng-icon', name: 'lucideInfo' },
  },
};
