import { ColorTokens, ThemePreset } from '@semiui/tokens';

/** One UI's elevation reads as a soft, close, mid-opacity shadow -- present enough to lift a card
 * off the page (unlike Cupertino's barely-there blur), but nowhere near Material's crisp layered
 * key+ambient pairs. Sits deliberately between those two references. */
const softShadow = '0 4px 16px rgb(0 0 0 / 0.14)';
const softShadowLg = '0 12px 36px rgb(0 0 0 / 0.22)';

/** One UI's system blue -- #0381fe (light) / #3e91ff (dark) are the actual values from Samsung's
 * One UI color documentation (developer.samsung.com/one-ui/color/system.html), used across
 * floating action buttons, sliders, checkboxes, and switches. Distinct from Samsung's corporate
 * brand blue (#1428a0), which is a separate, print/marketing-oriented token. Dark mode's
 * background goes to true black -- One UI has marketed AMOLED "true black" dark mode as a battery
 * feature since its earliest releases, same instinct as Cupertino's OLED black but arrived at
 * independently. Everything else follows One UI's stated "monotone" principle: plain grays, no
 * color tint mixed in, unlike Fluent's blue-tinted neutrals. */
const lightColor: ColorTokens = {
  background: '#ffffff',
  foreground: '#191919',
  primary: '#0381fe',
  primaryForeground: '#ffffff',
  destructive: '#ff5252',
  destructiveForeground: '#ffffff',
  border: '#e8e8ea',
  ring: '#0381fe',
  muted: '#f5f5f7',
  mutedForeground: '#8a8a8e',
};

const darkColor: ColorTokens = {
  background: '#000000',
  foreground: '#f2f2f2',
  primary: '#3e91ff',
  primaryForeground: '#ffffff',
  destructive: '#ff6b6b',
  destructiveForeground: '#000000',
  border: '#2c2c2e',
  ring: '#3e91ff',
  muted: '#1c1c1e',
  mutedForeground: '#9a9a9e',
};

export const Samsung: ThemePreset = {
  name: 'samsung',
  tokens: {
    color: lightColor,
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
      xl: '1.5rem',
    },
    // One UI's defining shape trait -- the "focus block" card, a rounded rectangle noticeably
    // bigger than iOS's already-generous continuous corners, sized to match how far a thumb
    // naturally curls on a large-screen phone. Buttons stay a big rounded rectangle rather than a
    // full capsule (unlike Cupertino) -- One UI reserves true pills for switches/sliders/tags.
    radius: {
      sm: '0.75rem',
      md: '1.25rem',
      lg: '1.75rem',
      full: '9999px',
    },
    typography: {
      fontFamily: '"SamsungOne", "Noto Sans", Roboto, system-ui, sans-serif',
      fontSizeSm: '0.875rem',
      fontSizeMd: '1rem',
      fontWeightMedium: '600',
    },
    comp: {
      button: {
        radius: 'var(--semiui-radius-lg)',
        fontWeight: '600',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        paddingX: { sm: '1rem', md: '1.375rem', lg: '1.75rem' },
        paddingY: { sm: '0.5rem', md: '0.6875rem', lg: '0.875rem' },
        fontSize: { sm: '0.8125rem', md: '0.9375rem', lg: '1.0625rem' },
        variants: {
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'var(--semiui-color-primary)',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-muted)',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          success: {
            background: '#00c896',
            foreground: '#ffffff',
            border: '#00c896',
          },
          info: {
            background: '#0381fe',
            foreground: '#ffffff',
            border: '#0381fe',
          },
          warn: {
            background: '#ffa000',
            foreground: '#ffffff',
            border: '#ffa000',
          },
          help: {
            background: '#9c6ade',
            foreground: '#ffffff',
            border: '#9c6ade',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'var(--semiui-color-foreground)',
          },
          link: {
            background: 'transparent',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
        },
      },
      input: {
        paddingX: '0.875rem',
        paddingY: '0.625rem',
        radius: 'var(--semiui-radius-sm)',
        fontSize: '0.9375rem',
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'transparent',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      select: {
        paddingX: '0.875rem',
        paddingY: '0.625rem',
        radius: 'var(--semiui-radius-sm)',
        fontSize: '0.9375rem',
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'transparent',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'transparent',
        panelShadow: softShadow,
        optionForeground: 'var(--semiui-color-foreground)',
        optionBackgroundHover: 'var(--semiui-color-muted)',
        optionBackgroundSelected: 'var(--semiui-color-primary)',
        optionForegroundSelected: 'var(--semiui-color-primary-foreground)',
      },
      switch: {
        // Switches (and only switches) go full pill -- true to One UI, where the track/thumb
        // toggle is one of the few controls that keeps the older fully-round Android shape.
        trackPadding: '0.125rem',
        trackBorderWidth: '0px',
        radius: 'var(--semiui-radius-full)',
        background: 'var(--semiui-color-border)',
        backgroundChecked: 'var(--semiui-color-primary)',
        border: 'transparent',
        borderChecked: 'var(--semiui-color-primary)',
        thumbBackground: '#ffffff',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        transitionDuration: '0.2s',
        trackWidth: { sm: '2rem', md: '2.75rem', lg: '3.5rem' },
        trackHeight: { sm: '1.125rem', md: '1.5rem', lg: '1.875rem' },
        thumbSize: { sm: '0.875rem', md: '1.125rem', lg: '1.5rem' },
      },
      checkbox: {
        radius: 'var(--semiui-radius-sm)',
        border: 'var(--semiui-color-muted-foreground)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundChecked: 'var(--semiui-color-primary)',
        foregroundChecked: '#ffffff',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      radio: {
        border: 'var(--semiui-color-muted-foreground)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        dotBackground: 'var(--semiui-color-primary)',
        focusRing: 'var(--semiui-color-ring)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      popover: {
        background: 'var(--semiui-color-background)',
        border: 'transparent',
        shadow: softShadow,
        radius: 'var(--semiui-radius-md)',
        foreground: 'var(--semiui-color-foreground)',
        paddingX: '1rem',
        paddingY: '0.75rem',
      },
      tooltip: {
        background: 'color-mix(in srgb, var(--semiui-color-foreground) 92%, transparent)',
        foreground: 'var(--semiui-color-background)',
        radius: 'var(--semiui-radius-sm)',
        paddingX: '0.5rem',
        paddingY: '0.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
      },
      skeleton: {
        background: 'var(--semiui-color-muted)',
        shimmer: 'color-mix(in srgb, var(--semiui-color-muted-foreground) 20%, transparent)',
        radius: 'var(--semiui-radius-sm)',
      },
      avatar: {
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        radius: 'var(--semiui-radius-full)',
        statusOnline: '#00c896',
        statusAway: '#ffa000',
        statusBusy: '#ff5252',
        statusOffline: '#8a8a8e',
        size: { sm: '1.75rem', md: '2.5rem', lg: '3.5rem', xl: '5rem' },
        fontSize: { sm: '0.625rem', md: '0.875rem', lg: '1.125rem', xl: '1.5rem' },
      },
      tag: {
        radius: 'var(--semiui-radius-full)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        paddingX: '0.625rem',
        paddingY: '0.125rem',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'color-mix(in srgb, var(--semiui-color-primary) 15%, transparent)',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-muted-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          danger: {
            background: 'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          success: {
            background: 'color-mix(in srgb, #00c896 15%, transparent)',
            foreground: '#00875f',
            border: 'transparent',
          },
          info: {
            background: 'color-mix(in srgb, #0381fe 15%, transparent)',
            foreground: '#0072de',
            border: 'transparent',
          },
          warn: {
            background: 'color-mix(in srgb, #ffa000 15%, transparent)',
            foreground: '#ffa000',
            border: 'transparent',
          },
          help: {
            background: 'color-mix(in srgb, #9c6ade 15%, transparent)',
            foreground: '#9c6ade',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'transparent',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      breadcrumb: {
        foreground: 'var(--semiui-color-muted-foreground)',
        currentForeground: 'var(--semiui-color-foreground)',
        separatorColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: '0.375rem',
      },
      badge: {
        size: '1.25rem',
        dotSize: '0.625rem',
        fontSize: '0.6875rem',
        ringColor: 'var(--semiui-color-background)',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          success: {
            background: '#00c896',
            foreground: '#ffffff',
            border: 'transparent',
          },
          info: {
            background: '#0381fe',
            foreground: '#ffffff',
            border: 'transparent',
          },
          warn: {
            background: '#ffa000',
            foreground: '#ffffff',
            border: 'transparent',
          },
          help: {
            background: '#9c6ade',
            foreground: '#ffffff',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      pagination: {
        radius: 'var(--semiui-radius-md)',
        gap: '0.25rem',
        size: '2.25rem',
        border: 'transparent',
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        backgroundHover: 'var(--semiui-color-border)',
        backgroundActive: 'var(--semiui-color-primary)',
        foregroundActive: 'var(--semiui-color-primary-foreground)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      rating: {
        filledColor: '#ffa000',
        emptyColor: 'var(--semiui-color-border)',
        gap: '0',
        size: { sm: '1.25rem', md: '2rem', lg: '2.75rem' },
      },
      accordion: {
        border: 'transparent',
        radius: 'var(--semiui-radius-md)',
        headerBackground: 'var(--semiui-color-muted)',
        headerBackgroundHover: 'var(--semiui-color-border)',
        headerForeground: 'var(--semiui-color-foreground)',
        panelBackground: 'var(--semiui-color-muted)',
        panelForeground: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      tabs: {
        border: 'transparent',
        gap: 'var(--semiui-spacing-md)',
        foreground: 'var(--semiui-color-muted-foreground)',
        foregroundActive: 'var(--semiui-color-primary)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        indicatorColor: 'var(--semiui-color-primary)',
        indicatorThickness: '2px',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      stepper: {
        circleSize: '2rem',
        circleBorder: 'transparent',
        circleBackground: 'var(--semiui-color-muted)',
        circleForeground: 'var(--semiui-color-muted-foreground)',
        circleBackgroundActive: 'var(--semiui-color-primary)',
        circleForegroundActive: 'var(--semiui-color-primary-foreground)',
        circleBackgroundCompleted: 'var(--semiui-color-primary)',
        circleForegroundCompleted: 'var(--semiui-color-primary-foreground)',
        connectorColor: 'var(--semiui-color-border)',
        connectorColorCompleted: 'var(--semiui-color-primary)',
        labelColor: 'var(--semiui-color-muted-foreground)',
        labelColorActive: 'var(--semiui-color-foreground)',
        descriptionColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: 'var(--semiui-spacing-sm)',
      },
      slider: {
        trackSize: '0.25rem',
        trackColor: 'var(--semiui-color-muted)',
        fillColor: 'var(--semiui-color-primary)',
        thumbSize: '1.5rem',
        thumbBackground: '#ffffff',
        thumbBorder: 'transparent',
        thumbBorderFocus: 'var(--semiui-color-ring)',
        tickColor: 'var(--semiui-color-border)',
        tickSize: '0.25rem',
        bubbleBackground: 'var(--semiui-color-foreground)',
        bubbleForeground: 'var(--semiui-color-background)',
      },
      chart: {
        gridColor: 'var(--semiui-color-border)',
        axisLabelColor: 'var(--semiui-color-muted-foreground)',
        axisLabelFontSize: '9px',
        tooltipBackground: 'color-mix(in srgb, var(--semiui-color-foreground) 92%, transparent)',
        tooltipForeground: 'var(--semiui-color-background)',
        tooltipRadius: 'var(--semiui-radius-sm)',
        legendFontSize: 'var(--semiui-typography-font-size-sm)',
        legendGap: 'var(--semiui-spacing-md)',
        lineStrokeWidth: '2',
        areaOpacity: '0.15',
      },
      table: {
        border: 'transparent',
        radius: 'var(--semiui-radius-md)',
        headerBackground: 'var(--semiui-color-muted)',
        headerForeground: 'var(--semiui-color-foreground)',
        rowBackground: 'var(--semiui-color-background)',
        rowBackgroundStriped: 'var(--semiui-color-muted)',
        rowBackgroundHover: 'var(--semiui-color-muted)',
        rowBackgroundSelected: 'color-mix(in srgb, var(--semiui-color-primary) 12%, transparent)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        cellPaddingX: 'var(--semiui-spacing-md)',
        cellPaddingY: 'var(--semiui-spacing-sm)',
        sortIconColor: 'var(--semiui-color-muted-foreground)',
        sortIconColorActive: 'var(--semiui-color-foreground)',
      },
      colorPicker: {
        svAreaSize: '12rem',
        hueTrackHeight: '0.75rem',
        thumbSize: '1rem',
        hueThumbWidth: '0.75rem',
        presetSize: '1.5rem',
        presetGap: '0.375rem',
        presetBorder: 'var(--semiui-color-border)',
        presetBorderSelected: 'var(--semiui-color-primary)',
      },
      datePicker: {
        daySize: '2.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        dayForeground: 'var(--semiui-color-foreground)',
        dayForegroundOutsideMonth: 'var(--semiui-color-muted-foreground)',
        dayBackgroundHover: 'var(--semiui-color-muted)',
        dayBackgroundSelected: 'var(--semiui-color-primary)',
        dayForegroundSelected: 'var(--semiui-color-primary-foreground)',
        dayBorderToday: 'var(--semiui-color-primary)',
        navBackgroundHover: 'var(--semiui-color-muted)',
        weekdayForeground: 'var(--semiui-color-muted-foreground)',
        monthLabelForeground: 'var(--semiui-color-foreground)',
      },
      carousel: {
        radius: 'var(--semiui-radius-lg)',
        arrowSize: '2.5rem',
        arrowBackground: 'rgb(0 0 0 / 0.3)',
        arrowBackgroundHover: 'rgb(0 0 0 / 0.5)',
        arrowColor: '#fff',
        dotSize: '0.5rem',
        dotColor: 'var(--semiui-color-border)',
        dotColorActive: 'var(--semiui-color-primary)',
        dotGap: 'var(--semiui-spacing-xs)',
      },
      toast: {
        radius: 'var(--semiui-radius-md)',
        shadow: softShadow,
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
        gap: 'var(--semiui-spacing-sm)',
        width: '24rem',
        blur: 'blur(12px)',
        variants: {
          default: {
            background: 'color-mix(in srgb, var(--semiui-color-background) 92%, transparent)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: 'var(--semiui-color-muted-foreground)',
          },
          success: {
            background: 'color-mix(in srgb, #00c896 16%, color-mix(in srgb, var(--semiui-color-background) 92%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#00c896',
          },
          error: {
            background:
              'color-mix(in srgb, var(--semiui-color-destructive) 16%, color-mix(in srgb, var(--semiui-color-background) 92%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: 'var(--semiui-color-destructive)',
          },
          warning: {
            background: 'color-mix(in srgb, #ffa000 16%, color-mix(in srgb, var(--semiui-color-background) 92%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#ffa000',
          },
          info: {
            background: 'color-mix(in srgb, #0381fe 16%, color-mix(in srgb, var(--semiui-color-background) 92%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#0381fe',
          },
        },
      },
      fileUpload: {
        border: 'var(--semiui-color-border)',
        borderDragOver: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-muted)',
        backgroundDragOver: 'var(--semiui-color-border)',
        radius: 'var(--semiui-radius-lg)',
        iconColor: 'var(--semiui-color-muted-foreground)',
        hintColor: 'var(--semiui-color-foreground)',
        acceptColor: 'var(--semiui-color-muted-foreground)',
        itemBackground: 'var(--semiui-color-background)',
        itemBorder: 'var(--semiui-color-border)',
        itemRadius: 'var(--semiui-radius-md)',
        thumbSize: '2.5rem',
        rejectionColor: 'var(--semiui-color-destructive)',
      },
      dialog: {
        backdropColor: 'rgb(0 0 0 / 0.45)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'transparent',
        radius: 'var(--semiui-radius-lg)',
        shadow: softShadowLg,
        headerBorder: 'var(--semiui-color-border)',
        footerBorder: 'var(--semiui-color-border)',
        titleFontSize: '1.0625rem',
        titleFontWeight: '600',
        padding: 'var(--semiui-spacing-lg)',
        widths: { sm: '24rem', md: '32rem', lg: '48rem', full: 'calc(100vw - 2rem)' },
      },
    },
  },
  darkColor,
  icons: {
    loading: { type: 'ng-icon', name: 'lucideLoaderCircle' },
    chevronDown: { type: 'ng-icon', name: 'lucideChevronDown' },
    clear: { type: 'ng-icon', name: 'lucideX' },
    passwordShow: { type: 'ng-icon', name: 'lucideEye' },
    passwordHide: { type: 'ng-icon', name: 'lucideEyeOff' },
    checkboxCheck: { type: 'ng-icon', name: 'lucideCheck' },
    checkboxIndeterminate: { type: 'ng-icon', name: 'lucideMinus' },
    search: { type: 'ng-icon', name: 'lucideSearch' },
    plus: { type: 'ng-icon', name: 'lucidePlus' },
    minus: { type: 'ng-icon', name: 'lucideMinus' },
    avatarFallback: { type: 'ng-icon', name: 'lucideUser' },
    rating: { type: 'ng-icon', name: 'lucideStar' },
    upload: { type: 'ng-icon', name: 'lucideUpload' },
    file: { type: 'ng-icon', name: 'lucideFile' },
    toastSuccess: { type: 'ng-icon', name: 'lucideCircleCheck' },
    toastError: { type: 'ng-icon', name: 'lucideCircleX' },
    toastWarning: { type: 'ng-icon', name: 'lucideTriangleAlert' },
    toastInfo: { type: 'ng-icon', name: 'lucideInfo' },
  },
};
