import { ColorTokens, ThemePreset } from '@semiui/tokens';

/** Fluent 2's actual documented ambient+key shadow pairs (Shadow4/8/16/28) -- softer and much
 * lower-opacity than Material's elevation curves, but still layered rather than a single blur. */
const shadow4 = '0 0.3px 0.9px rgb(0 0 0 / 0.1), 0 1.6px 3.6px rgb(0 0 0 / 0.13)';
const shadow8 = '0 0.6px 1.8px rgb(0 0 0 / 0.1), 0 3.2px 7.2px rgb(0 0 0 / 0.13)';
const shadow16 = '0 1.2px 3.6px rgb(0 0 0 / 0.1), 0 6.4px 14.4px rgb(0 0 0 / 0.13)';
const shadow28 = '0 2.1px 6.4px rgb(0 0 0 / 0.1), 0 11.2px 25.6px rgb(0 0 0 / 0.13)';

/** The Microsoft blue anyone who's used Windows or Office recognizes on sight, plus Fluent's
 * documented neutral grey scale (#242424 text, #d1d1d1 stroke). */
const lightColor: ColorTokens = {
  background: '#ffffff',
  foreground: '#242424',
  primary: '#0078d4',
  primaryForeground: '#ffffff',
  destructive: '#d13438',
  destructiveForeground: '#ffffff',
  border: '#d1d1d1',
  ring: '#0078d4',
  muted: '#f5f5f5',
  mutedForeground: '#616161',
};

const darkColor: ColorTokens = {
  background: '#1f1f1f',
  foreground: '#ffffff',
  primary: '#479ef5',
  primaryForeground: '#1f1f1f',
  destructive: '#ff6a6a',
  destructiveForeground: '#1f1f1f',
  border: '#3b3a39',
  ring: '#479ef5',
  muted: '#2b2b2b',
  mutedForeground: '#c8c6c4',
};

export const Fluent: ThemePreset = {
  name: 'fluent',
  tokens: {
    color: lightColor,
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
      xl: '1.5rem',
    },
    // Fluent 2's modest corner radii -- 4px on controls, 8px on surfaces. Neither Material's
    // pills nor Carbon's sharp rectangles; its own, smaller, third shape signature.
    radius: {
      sm: '0.25rem',
      md: '0.25rem',
      lg: '0.5rem',
      full: '9999px',
    },
    typography: {
      fontFamily: '"Segoe UI", system-ui, sans-serif',
      fontSizeSm: '0.875rem',
      fontSizeMd: '1rem',
      fontWeightMedium: '600',
    },
    comp: {
      button: {
        radius: 'var(--semiui-radius-sm)',
        fontWeight: '600',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        paddingX: { sm: '0.75rem', md: '1rem', lg: '1.25rem' },
        paddingY: { sm: '0.375rem', md: '0.5rem', lg: '0.625rem' },
        fontSize: { sm: '0.8125rem', md: '0.875rem', lg: '1rem' },
        variants: {
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'var(--semiui-color-primary)',
          },
          secondary: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          success: {
            background: '#107c10',
            foreground: '#ffffff',
            border: '#107c10',
          },
          info: {
            background: '#0078d4',
            foreground: '#ffffff',
            border: '#0078d4',
          },
          warn: {
            background: '#9d5d00',
            foreground: '#ffffff',
            border: '#9d5d00',
          },
          help: {
            background: '#5b2c6f',
            foreground: '#ffffff',
            border: '#5b2c6f',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'var(--semiui-color-foreground)',
          },
          link: {
            background: 'transparent',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
        },
      },
      input: {
        paddingX: '0.75rem',
        paddingY: '0.5rem',
        radius: 'var(--semiui-radius-sm)',
        fontSize: '0.875rem',
        background: 'var(--semiui-color-background)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'var(--semiui-color-border)',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      select: {
        paddingX: '0.75rem',
        paddingY: '0.5rem',
        radius: 'var(--semiui-radius-sm)',
        fontSize: '0.875rem',
        background: 'var(--semiui-color-background)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'var(--semiui-color-border)',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'var(--semiui-color-border)',
        panelShadow: shadow16,
        optionForeground: 'var(--semiui-color-foreground)',
        optionBackgroundHover: 'var(--semiui-color-muted)',
        optionBackgroundSelected: 'var(--semiui-color-primary)',
        optionForegroundSelected: 'var(--semiui-color-primary-foreground)',
      },
      switch: {
        trackPadding: '0.125rem',
        trackBorderWidth: '1px',
        radius: 'var(--semiui-radius-full)',
        background: 'var(--semiui-color-muted-foreground)',
        backgroundChecked: 'var(--semiui-color-primary)',
        border: 'transparent',
        borderChecked: 'var(--semiui-color-primary)',
        thumbBackground: 'var(--semiui-color-background)',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        transitionDuration: '0.15s',
        trackWidth: { sm: '2rem', md: '2.75rem', lg: '3.5rem' },
        trackHeight: { sm: '1.125rem', md: '1.5rem', lg: '1.875rem' },
        thumbSize: { sm: '0.875rem', md: '1.125rem', lg: '1.5rem' },
      },
      checkbox: {
        radius: '0.1875rem',
        border: 'var(--semiui-color-muted-foreground)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundChecked: 'var(--semiui-color-primary)',
        foregroundChecked: 'var(--semiui-color-primary-foreground)',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      radio: {
        border: 'var(--semiui-color-muted-foreground)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        dotBackground: 'var(--semiui-color-primary)',
        focusRing: 'var(--semiui-color-ring)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      popover: {
        background: 'var(--semiui-color-background)',
        border: 'var(--semiui-color-border)',
        shadow: shadow16,
        radius: 'var(--semiui-radius-lg)',
        foreground: 'var(--semiui-color-foreground)',
        paddingX: '1rem',
        paddingY: '0.75rem',
      },
      tooltip: {
        background: '#1f1f1f',
        foreground: '#ffffff',
        radius: 'var(--semiui-radius-sm)',
        paddingX: '0.5rem',
        paddingY: '0.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
      },
      skeleton: {
        background: 'var(--semiui-color-muted)',
        shimmer: 'color-mix(in srgb, var(--semiui-color-muted-foreground) 20%, transparent)',
        radius: 'var(--semiui-radius-sm)',
      },
      avatar: {
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        radius: 'var(--semiui-radius-full)',
        statusOnline: '#107c10',
        statusAway: '#9d5d00',
        statusBusy: '#d13438',
        statusOffline: '#8a8886',
        size: { sm: '1.75rem', md: '2.5rem', lg: '3.5rem', xl: '5rem' },
        fontSize: { sm: '0.625rem', md: '0.875rem', lg: '1.125rem', xl: '1.5rem' },
      },
      tag: {
        radius: 'var(--semiui-radius-sm)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        paddingX: '0.5rem',
        paddingY: '0.125rem',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'color-mix(in srgb, var(--semiui-color-primary) 15%, transparent)',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-muted-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          danger: {
            background: 'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          success: {
            background: 'color-mix(in srgb, #107c10 15%, transparent)',
            foreground: '#107c10',
            border: 'transparent',
          },
          info: {
            background: 'color-mix(in srgb, #0078d4 15%, transparent)',
            foreground: '#0078d4',
            border: 'transparent',
          },
          warn: {
            background: 'color-mix(in srgb, #9d5d00 15%, transparent)',
            foreground: '#9d5d00',
            border: 'transparent',
          },
          help: {
            background: 'color-mix(in srgb, #5b2c6f 15%, transparent)',
            foreground: '#5b2c6f',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'transparent',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      breadcrumb: {
        foreground: 'var(--semiui-color-muted-foreground)',
        currentForeground: 'var(--semiui-color-foreground)',
        separatorColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: '0.375rem',
      },
      badge: {
        size: '1.25rem',
        dotSize: '0.625rem',
        fontSize: '0.6875rem',
        ringColor: 'var(--semiui-color-background)',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          success: {
            background: '#107c10',
            foreground: '#ffffff',
            border: 'transparent',
          },
          info: {
            background: '#0078d4',
            foreground: '#ffffff',
            border: 'transparent',
          },
          warn: {
            background: '#9d5d00',
            foreground: '#ffffff',
            border: 'transparent',
          },
          help: {
            background: '#5b2c6f',
            foreground: '#ffffff',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      pagination: {
        radius: 'var(--semiui-radius-sm)',
        gap: '0.25rem',
        size: '2.25rem',
        border: 'var(--semiui-color-border)',
        background: 'transparent',
        foreground: 'var(--semiui-color-foreground)',
        backgroundHover: 'var(--semiui-color-muted)',
        backgroundActive: 'var(--semiui-color-primary)',
        foregroundActive: 'var(--semiui-color-primary-foreground)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      rating: {
        filledColor: '#ffb900',
        emptyColor: 'var(--semiui-color-border)',
        gap: '0',
        size: { sm: '1.25rem', md: '2rem', lg: '2.75rem' },
      },
      accordion: {
        border: 'var(--semiui-color-border)',
        radius: 'var(--semiui-radius-md)',
        headerBackground: 'transparent',
        headerBackgroundHover: 'var(--semiui-color-muted)',
        headerForeground: 'var(--semiui-color-foreground)',
        panelBackground: 'transparent',
        panelForeground: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      tabs: {
        border: 'var(--semiui-color-border)',
        gap: 'var(--semiui-spacing-md)',
        foreground: 'var(--semiui-color-muted-foreground)',
        foregroundActive: 'var(--semiui-color-primary)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        indicatorColor: 'var(--semiui-color-primary)',
        indicatorThickness: '2px',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      stepper: {
        circleSize: '2rem',
        circleBorder: 'var(--semiui-color-border)',
        circleBackground: 'var(--semiui-color-background)',
        circleForeground: 'var(--semiui-color-muted-foreground)',
        circleBackgroundActive: 'var(--semiui-color-primary)',
        circleForegroundActive: 'var(--semiui-color-primary-foreground)',
        circleBackgroundCompleted: 'var(--semiui-color-primary)',
        circleForegroundCompleted: 'var(--semiui-color-primary-foreground)',
        connectorColor: 'var(--semiui-color-border)',
        connectorColorCompleted: 'var(--semiui-color-primary)',
        labelColor: 'var(--semiui-color-muted-foreground)',
        labelColorActive: 'var(--semiui-color-foreground)',
        descriptionColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: 'var(--semiui-spacing-sm)',
      },
      slider: {
        trackSize: '0.25rem',
        trackColor: 'var(--semiui-color-muted)',
        fillColor: 'var(--semiui-color-primary)',
        thumbSize: '1.125rem',
        thumbBackground: 'var(--semiui-color-background)',
        thumbBorder: 'var(--semiui-color-primary)',
        thumbBorderFocus: 'var(--semiui-color-ring)',
        tickColor: 'var(--semiui-color-border)',
        tickSize: '0.25rem',
        bubbleBackground: 'var(--semiui-color-foreground)',
        bubbleForeground: 'var(--semiui-color-background)',
      },
      chart: {
        gridColor: 'var(--semiui-color-border)',
        axisLabelColor: 'var(--semiui-color-muted-foreground)',
        axisLabelFontSize: '9px',
        tooltipBackground: '#1f1f1f',
        tooltipForeground: '#ffffff',
        tooltipRadius: 'var(--semiui-radius-sm)',
        legendFontSize: 'var(--semiui-typography-font-size-sm)',
        legendGap: 'var(--semiui-spacing-md)',
        lineStrokeWidth: '2',
        areaOpacity: '0.15',
      },
      table: {
        border: 'var(--semiui-color-border)',
        radius: 'var(--semiui-radius-md)',
        headerBackground: 'var(--semiui-color-muted)',
        headerForeground: 'var(--semiui-color-foreground)',
        rowBackground: 'var(--semiui-color-background)',
        rowBackgroundStriped: 'var(--semiui-color-muted)',
        rowBackgroundHover: 'var(--semiui-color-muted)',
        rowBackgroundSelected: 'color-mix(in srgb, var(--semiui-color-primary) 12%, transparent)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        cellPaddingX: 'var(--semiui-spacing-md)',
        cellPaddingY: 'var(--semiui-spacing-sm)',
        sortIconColor: 'var(--semiui-color-muted-foreground)',
        sortIconColorActive: 'var(--semiui-color-foreground)',
      },
      colorPicker: {
        svAreaSize: '12rem',
        hueTrackHeight: '0.75rem',
        thumbSize: '1rem',
        hueThumbWidth: '0.75rem',
        presetSize: '1.5rem',
        presetGap: '0.375rem',
        presetBorder: 'var(--semiui-color-border)',
        presetBorderSelected: 'var(--semiui-color-primary)',
      },
      datePicker: {
        daySize: '2.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        dayForeground: 'var(--semiui-color-foreground)',
        dayForegroundOutsideMonth: 'var(--semiui-color-muted-foreground)',
        dayBackgroundHover: 'var(--semiui-color-muted)',
        dayBackgroundSelected: 'var(--semiui-color-primary)',
        dayForegroundSelected: 'var(--semiui-color-primary-foreground)',
        dayBorderToday: 'var(--semiui-color-primary)',
        navBackgroundHover: 'var(--semiui-color-muted)',
        weekdayForeground: 'var(--semiui-color-muted-foreground)',
        monthLabelForeground: 'var(--semiui-color-foreground)',
      },
      carousel: {
        radius: 'var(--semiui-radius-lg)',
        arrowSize: '2.5rem',
        arrowBackground: 'rgb(0 0 0 / 0.4)',
        arrowBackgroundHover: 'rgb(0 0 0 / 0.6)',
        arrowColor: '#fff',
        dotSize: '0.5rem',
        dotColor: 'var(--semiui-color-border)',
        dotColorActive: 'var(--semiui-color-primary)',
        dotGap: 'var(--semiui-spacing-xs)',
      },
      toast: {
        radius: 'var(--semiui-radius-lg)',
        shadow: shadow8,
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
        gap: 'var(--semiui-spacing-sm)',
        width: '24rem',
        blur: 'none',
        variants: {
          default: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
            iconColor: 'var(--semiui-color-muted-foreground)',
          },
          success: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: '#107c10',
            iconColor: '#107c10',
          },
          error: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-destructive)',
            iconColor: 'var(--semiui-color-destructive)',
          },
          warning: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: '#9d5d00',
            iconColor: '#9d5d00',
          },
          info: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: '#0078d4',
            iconColor: '#0078d4',
          },
        },
      },
      fileUpload: {
        border: 'var(--semiui-color-border)',
        borderDragOver: 'var(--semiui-color-primary)',
        background: 'transparent',
        backgroundDragOver: 'var(--semiui-color-muted)',
        radius: 'var(--semiui-radius-lg)',
        iconColor: 'var(--semiui-color-muted-foreground)',
        hintColor: 'var(--semiui-color-foreground)',
        acceptColor: 'var(--semiui-color-muted-foreground)',
        itemBackground: 'var(--semiui-color-muted)',
        itemBorder: 'var(--semiui-color-border)',
        itemRadius: 'var(--semiui-radius-md)',
        thumbSize: '2.5rem',
        rejectionColor: 'var(--semiui-color-destructive)',
      },
      dialog: {
        backdropColor: 'rgb(0 0 0 / 0.4)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'var(--semiui-color-border)',
        radius: 'var(--semiui-radius-lg)',
        shadow: shadow28,
        headerBorder: 'var(--semiui-color-border)',
        footerBorder: 'var(--semiui-color-border)',
        titleFontSize: '1.125rem',
        titleFontWeight: '600',
        padding: 'var(--semiui-spacing-lg)',
        widths: { sm: '24rem', md: '32rem', lg: '48rem', full: 'calc(100vw - 2rem)' },
      },
    },
  },
  darkColor,
  icons: {
    loading: { type: 'ng-icon', name: 'lucideLoaderCircle' },
    chevronDown: { type: 'ng-icon', name: 'lucideChevronDown' },
    clear: { type: 'ng-icon', name: 'lucideX' },
    passwordShow: { type: 'ng-icon', name: 'lucideEye' },
    passwordHide: { type: 'ng-icon', name: 'lucideEyeOff' },
    checkboxCheck: { type: 'ng-icon', name: 'lucideCheck' },
    checkboxIndeterminate: { type: 'ng-icon', name: 'lucideMinus' },
    search: { type: 'ng-icon', name: 'lucideSearch' },
    plus: { type: 'ng-icon', name: 'lucidePlus' },
    minus: { type: 'ng-icon', name: 'lucideMinus' },
    avatarFallback: { type: 'ng-icon', name: 'lucideUser' },
    rating: { type: 'ng-icon', name: 'lucideStar' },
    upload: { type: 'ng-icon', name: 'lucideUpload' },
    file: { type: 'ng-icon', name: 'lucideFile' },
    toastSuccess: { type: 'ng-icon', name: 'lucideCircleCheck' },
    toastError: { type: 'ng-icon', name: 'lucideCircleX' },
    toastWarning: { type: 'ng-icon', name: 'lucideTriangleAlert' },
    toastInfo: { type: 'ng-icon', name: 'lucideInfo' },
  },
};
