import { ColorTokens, ThemePreset } from '@semiui/tokens';

/** iOS's shadows are soft, diffuse, and low-opacity -- big blur radius, barely-there spread --
 * the opposite instinct from Material's crisp layered elevation or Fluent's tight ambient+key
 * pairs. Panels lean on this plus translucency (see `toast.blur` below) rather than a hard edge. */
const softShadow = '0 8px 30px rgb(0 0 0 / 0.12)';
const softShadowLg = '0 20px 60px rgb(0 0 0 / 0.2)';

/** iOS system colors -- #007aff and OLED-black #000000 dark mode are as recognizable as design
 * tokens get to anyone who's used an iPhone. */
const lightColor: ColorTokens = {
  background: '#ffffff',
  foreground: '#000000',
  primary: '#007aff',
  primaryForeground: '#ffffff',
  destructive: '#ff3b30',
  destructiveForeground: '#ffffff',
  border: '#e5e5ea',
  ring: '#007aff',
  muted: '#f2f2f7',
  mutedForeground: '#8e8e93',
};

const darkColor: ColorTokens = {
  background: '#000000',
  foreground: '#ffffff',
  primary: '#0a84ff',
  primaryForeground: '#ffffff',
  destructive: '#ff453a',
  destructiveForeground: '#ffffff',
  border: '#38383a',
  ring: '#0a84ff',
  muted: '#1c1c1e',
  mutedForeground: '#98989d',
};

export const Cupertino: ThemePreset = {
  name: 'cupertino',
  tokens: {
    color: lightColor,
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
      xl: '1.5rem',
    },
    // Generously rounded, but not uniformly pill like Material -- iOS's continuous-corner card
    // shape (~14-20px) shows up on surfaces, while capsule shapes are reserved for buttons.
    radius: {
      sm: '0.5rem',
      md: '0.875rem',
      lg: '1.25rem',
      full: '9999px',
    },
    typography: {
      fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", system-ui, sans-serif',
      fontSizeSm: '0.875rem',
      fontSizeMd: '1rem',
      fontWeightMedium: '600',
    },
    comp: {
      button: {
        // The capsule "GET"/"Continue" button shape used everywhere in modern iOS.
        radius: 'var(--semiui-radius-full)',
        fontWeight: '600',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        paddingX: { sm: '1rem', md: '1.5rem', lg: '2rem' },
        paddingY: { sm: '0.4375rem', md: '0.625rem', lg: '0.8125rem' },
        fontSize: { sm: '0.8125rem', md: '0.9375rem', lg: '1.0625rem' },
        variants: {
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'var(--semiui-color-primary)',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-primary)',
            border: 'var(--semiui-color-muted)',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          success: {
            background: '#34c759',
            foreground: '#ffffff',
            border: '#34c759',
          },
          info: {
            background: '#5ac8fa',
            foreground: '#ffffff',
            border: '#5ac8fa',
          },
          warn: {
            background: '#ff9500',
            foreground: '#ffffff',
            border: '#ff9500',
          },
          help: {
            background: '#af52de',
            foreground: '#ffffff',
            border: '#af52de',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'var(--semiui-color-foreground)',
          },
          link: {
            background: 'transparent',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
        },
      },
      input: {
        paddingX: '0.75rem',
        paddingY: '0.625rem',
        radius: 'var(--semiui-radius-sm)',
        fontSize: '0.9375rem',
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'transparent',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      select: {
        paddingX: '0.75rem',
        paddingY: '0.625rem',
        radius: 'var(--semiui-radius-sm)',
        fontSize: '0.9375rem',
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'transparent',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'transparent',
        panelShadow: softShadow,
        optionForeground: 'var(--semiui-color-foreground)',
        optionBackgroundHover: 'var(--semiui-color-muted)',
        optionBackgroundSelected: 'var(--semiui-color-primary)',
        optionForegroundSelected: 'var(--semiui-color-primary-foreground)',
      },
      switch: {
        trackPadding: '0.125rem',
        trackBorderWidth: '0px',
        radius: 'var(--semiui-radius-full)',
        background: 'var(--semiui-color-border)',
        backgroundChecked: '#34c759',
        border: 'transparent',
        borderChecked: '#34c759',
        thumbBackground: '#ffffff',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        transitionDuration: '0.2s',
        trackWidth: { sm: '2rem', md: '2.75rem', lg: '3.5rem' },
        trackHeight: { sm: '1.125rem', md: '1.5rem', lg: '1.875rem' },
        thumbSize: { sm: '0.875rem', md: '1.125rem', lg: '1.5rem' },
      },
      checkbox: {
        radius: 'var(--semiui-radius-full)',
        border: 'var(--semiui-color-muted-foreground)',
        borderChecked: '#007aff',
        background: 'var(--semiui-color-background)',
        backgroundChecked: '#007aff',
        foregroundChecked: '#ffffff',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      radio: {
        border: 'var(--semiui-color-muted-foreground)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        dotBackground: 'var(--semiui-color-primary)',
        focusRing: 'var(--semiui-color-ring)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      popover: {
        background: 'var(--semiui-color-background)',
        border: 'transparent',
        shadow: softShadow,
        radius: 'var(--semiui-radius-md)',
        foreground: 'var(--semiui-color-foreground)',
        paddingX: '1rem',
        paddingY: '0.75rem',
      },
      tooltip: {
        background: 'color-mix(in srgb, var(--semiui-color-foreground) 90%, transparent)',
        foreground: 'var(--semiui-color-background)',
        radius: 'var(--semiui-radius-sm)',
        paddingX: '0.5rem',
        paddingY: '0.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
      },
      skeleton: {
        background: 'var(--semiui-color-muted)',
        shimmer: 'color-mix(in srgb, var(--semiui-color-muted-foreground) 20%, transparent)',
        radius: 'var(--semiui-radius-sm)',
      },
      avatar: {
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        radius: 'var(--semiui-radius-full)',
        statusOnline: '#34c759',
        statusAway: '#ff9500',
        statusBusy: '#ff3b30',
        statusOffline: '#8e8e93',
        size: { sm: '1.75rem', md: '2.5rem', lg: '3.5rem', xl: '5rem' },
        fontSize: { sm: '0.625rem', md: '0.875rem', lg: '1.125rem', xl: '1.5rem' },
      },
      tag: {
        radius: 'var(--semiui-radius-full)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        paddingX: '0.625rem',
        paddingY: '0.125rem',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'color-mix(in srgb, var(--semiui-color-primary) 15%, transparent)',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-muted-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          danger: {
            background: 'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          success: {
            background: 'color-mix(in srgb, #34c759 15%, transparent)',
            foreground: '#248a3d',
            border: 'transparent',
          },
          info: {
            background: 'color-mix(in srgb, #5ac8fa 20%, transparent)',
            foreground: '#0071a4',
            border: 'transparent',
          },
          warn: {
            background: 'color-mix(in srgb, #ff9500 15%, transparent)',
            foreground: '#ff9500',
            border: 'transparent',
          },
          help: {
            background: 'color-mix(in srgb, #af52de 15%, transparent)',
            foreground: '#af52de',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'transparent',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      breadcrumb: {
        foreground: 'var(--semiui-color-muted-foreground)',
        currentForeground: 'var(--semiui-color-foreground)',
        separatorColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: '0.375rem',
      },
      badge: {
        size: '1.25rem',
        dotSize: '0.625rem',
        fontSize: '0.6875rem',
        ringColor: 'var(--semiui-color-background)',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          success: {
            background: '#34c759',
            foreground: '#ffffff',
            border: 'transparent',
          },
          info: {
            background: '#5ac8fa',
            foreground: '#ffffff',
            border: 'transparent',
          },
          warn: {
            background: '#ff9500',
            foreground: '#ffffff',
            border: 'transparent',
          },
          help: {
            background: '#af52de',
            foreground: '#ffffff',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      pagination: {
        radius: 'var(--semiui-radius-full)',
        gap: '0.25rem',
        size: '2.25rem',
        border: 'transparent',
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        backgroundHover: 'var(--semiui-color-border)',
        backgroundActive: 'var(--semiui-color-primary)',
        foregroundActive: 'var(--semiui-color-primary-foreground)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      rating: {
        filledColor: '#ffcc00',
        emptyColor: 'var(--semiui-color-border)',
        gap: '0',
        size: { sm: '1.25rem', md: '2rem', lg: '2.75rem' },
      },
      accordion: {
        border: 'transparent',
        radius: 'var(--semiui-radius-md)',
        headerBackground: 'var(--semiui-color-muted)',
        headerBackgroundHover: 'var(--semiui-color-border)',
        headerForeground: 'var(--semiui-color-foreground)',
        panelBackground: 'var(--semiui-color-muted)',
        panelForeground: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      tabs: {
        border: 'transparent',
        gap: 'var(--semiui-spacing-md)',
        foreground: 'var(--semiui-color-muted-foreground)',
        foregroundActive: 'var(--semiui-color-primary)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        indicatorColor: 'var(--semiui-color-primary)',
        indicatorThickness: '2px',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      stepper: {
        circleSize: '2rem',
        circleBorder: 'transparent',
        circleBackground: 'var(--semiui-color-muted)',
        circleForeground: 'var(--semiui-color-muted-foreground)',
        circleBackgroundActive: 'var(--semiui-color-primary)',
        circleForegroundActive: 'var(--semiui-color-primary-foreground)',
        circleBackgroundCompleted: 'var(--semiui-color-primary)',
        circleForegroundCompleted: 'var(--semiui-color-primary-foreground)',
        connectorColor: 'var(--semiui-color-border)',
        connectorColorCompleted: 'var(--semiui-color-primary)',
        labelColor: 'var(--semiui-color-muted-foreground)',
        labelColorActive: 'var(--semiui-color-foreground)',
        descriptionColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: 'var(--semiui-spacing-sm)',
      },
      slider: {
        trackSize: '0.25rem',
        trackColor: 'var(--semiui-color-muted)',
        fillColor: 'var(--semiui-color-primary)',
        thumbSize: '1.5rem',
        thumbBackground: '#ffffff',
        thumbBorder: 'transparent',
        thumbBorderFocus: 'var(--semiui-color-ring)',
        tickColor: 'var(--semiui-color-border)',
        tickSize: '0.25rem',
        bubbleBackground: 'var(--semiui-color-foreground)',
        bubbleForeground: 'var(--semiui-color-background)',
      },
      chart: {
        gridColor: 'var(--semiui-color-border)',
        axisLabelColor: 'var(--semiui-color-muted-foreground)',
        axisLabelFontSize: '9px',
        tooltipBackground: 'color-mix(in srgb, var(--semiui-color-foreground) 90%, transparent)',
        tooltipForeground: 'var(--semiui-color-background)',
        tooltipRadius: 'var(--semiui-radius-sm)',
        legendFontSize: 'var(--semiui-typography-font-size-sm)',
        legendGap: 'var(--semiui-spacing-md)',
        lineStrokeWidth: '2',
        areaOpacity: '0.15',
      },
      table: {
        border: 'transparent',
        radius: 'var(--semiui-radius-md)',
        headerBackground: 'var(--semiui-color-muted)',
        headerForeground: 'var(--semiui-color-foreground)',
        rowBackground: 'var(--semiui-color-background)',
        rowBackgroundStriped: 'var(--semiui-color-muted)',
        rowBackgroundHover: 'var(--semiui-color-muted)',
        rowBackgroundSelected: 'color-mix(in srgb, var(--semiui-color-primary) 12%, transparent)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        cellPaddingX: 'var(--semiui-spacing-md)',
        cellPaddingY: 'var(--semiui-spacing-sm)',
        sortIconColor: 'var(--semiui-color-muted-foreground)',
        sortIconColorActive: 'var(--semiui-color-foreground)',
      },
      colorPicker: {
        svAreaSize: '12rem',
        hueTrackHeight: '0.75rem',
        thumbSize: '1rem',
        hueThumbWidth: '0.75rem',
        presetSize: '1.5rem',
        presetGap: '0.375rem',
        presetBorder: 'var(--semiui-color-border)',
        presetBorderSelected: 'var(--semiui-color-primary)',
      },
      datePicker: {
        daySize: '2.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        dayForeground: 'var(--semiui-color-foreground)',
        dayForegroundOutsideMonth: 'var(--semiui-color-muted-foreground)',
        dayBackgroundHover: 'var(--semiui-color-muted)',
        dayBackgroundSelected: 'var(--semiui-color-primary)',
        dayForegroundSelected: 'var(--semiui-color-primary-foreground)',
        dayBorderToday: 'var(--semiui-color-primary)',
        navBackgroundHover: 'var(--semiui-color-muted)',
        weekdayForeground: 'var(--semiui-color-muted-foreground)',
        monthLabelForeground: 'var(--semiui-color-foreground)',
      },
      carousel: {
        radius: 'var(--semiui-radius-lg)',
        arrowSize: '2.5rem',
        arrowBackground: 'rgb(0 0 0 / 0.3)',
        arrowBackgroundHover: 'rgb(0 0 0 / 0.5)',
        arrowColor: '#fff',
        dotSize: '0.5rem',
        dotColor: 'var(--semiui-color-border)',
        dotColorActive: 'var(--semiui-color-primary)',
        dotGap: 'var(--semiui-spacing-xs)',
      },
      toast: {
        radius: 'var(--semiui-radius-md)',
        shadow: softShadow,
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
        gap: 'var(--semiui-spacing-sm)',
        width: '24rem',
        // A stronger frosted-glass blur than the other presets -- iOS's translucent-panel look
        // (Control Center, notification banners) leans on this more than any of the others.
        blur: 'blur(20px)',
        variants: {
          default: {
            background: 'color-mix(in srgb, var(--semiui-color-background) 75%, transparent)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: 'var(--semiui-color-muted-foreground)',
          },
          success: {
            background: 'color-mix(in srgb, #34c759 16%, color-mix(in srgb, var(--semiui-color-background) 75%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#34c759',
          },
          error: {
            background:
              'color-mix(in srgb, var(--semiui-color-destructive) 16%, color-mix(in srgb, var(--semiui-color-background) 75%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: 'var(--semiui-color-destructive)',
          },
          warning: {
            background: 'color-mix(in srgb, #ff9500 16%, color-mix(in srgb, var(--semiui-color-background) 75%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#ff9500',
          },
          info: {
            background: 'color-mix(in srgb, #5ac8fa 16%, color-mix(in srgb, var(--semiui-color-background) 75%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#5ac8fa',
          },
        },
      },
      fileUpload: {
        border: 'var(--semiui-color-border)',
        borderDragOver: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-muted)',
        backgroundDragOver: 'var(--semiui-color-border)',
        radius: 'var(--semiui-radius-lg)',
        iconColor: 'var(--semiui-color-muted-foreground)',
        hintColor: 'var(--semiui-color-foreground)',
        acceptColor: 'var(--semiui-color-muted-foreground)',
        itemBackground: 'var(--semiui-color-background)',
        itemBorder: 'var(--semiui-color-border)',
        itemRadius: 'var(--semiui-radius-md)',
        thumbSize: '2.5rem',
        rejectionColor: 'var(--semiui-color-destructive)',
      },
      dialog: {
        backdropColor: 'rgb(0 0 0 / 0.4)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'transparent',
        radius: 'var(--semiui-radius-lg)',
        shadow: softShadowLg,
        headerBorder: 'var(--semiui-color-border)',
        footerBorder: 'var(--semiui-color-border)',
        titleFontSize: '1.0625rem',
        titleFontWeight: '600',
        padding: 'var(--semiui-spacing-lg)',
        widths: { sm: '24rem', md: '32rem', lg: '48rem', full: 'calc(100vw - 2rem)' },
      },
    },
  },
  darkColor,
  icons: {
    loading: { type: 'ng-icon', name: 'lucideLoaderCircle' },
    chevronDown: { type: 'ng-icon', name: 'lucideChevronDown' },
    clear: { type: 'ng-icon', name: 'lucideX' },
    passwordShow: { type: 'ng-icon', name: 'lucideEye' },
    passwordHide: { type: 'ng-icon', name: 'lucideEyeOff' },
    checkboxCheck: { type: 'ng-icon', name: 'lucideCheck' },
    checkboxIndeterminate: { type: 'ng-icon', name: 'lucideMinus' },
    search: { type: 'ng-icon', name: 'lucideSearch' },
    plus: { type: 'ng-icon', name: 'lucidePlus' },
    minus: { type: 'ng-icon', name: 'lucideMinus' },
    avatarFallback: { type: 'ng-icon', name: 'lucideUser' },
    rating: { type: 'ng-icon', name: 'lucideStar' },
    upload: { type: 'ng-icon', name: 'lucideUpload' },
    file: { type: 'ng-icon', name: 'lucideFile' },
    toastSuccess: { type: 'ng-icon', name: 'lucideCircleCheck' },
    toastError: { type: 'ng-icon', name: 'lucideCircleX' },
    toastWarning: { type: 'ng-icon', name: 'lucideTriangleAlert' },
    toastInfo: { type: 'ng-icon', name: 'lucideInfo' },
  },
};
