import { ColorTokens, ThemePreset } from '@semiui/tokens';

const lightColor: ColorTokens = {
  background: '#ffffff',
  foreground: '#0f172a',
  primary: '#3b82f6',
  primaryForeground: '#ffffff',
  destructive: '#dc2626',
  destructiveForeground: '#ffffff',
  border: '#e2e8f0',
  ring: '#3b82f6',
  muted: '#f1f5f9',
  mutedForeground: '#64748b',
};

const darkColor: ColorTokens = {
  background: '#0b1120',
  foreground: '#e2e8f0',
  primary: '#60a5fa',
  primaryForeground: '#0b1220',
  destructive: '#f87171',
  destructiveForeground: '#0b1220',
  border: '#1e293b',
  ring: '#60a5fa',
  muted: '#111827',
  mutedForeground: '#94a3b8',
};

export const Semi: ThemePreset = {
  name: 'semi',
  tokens: {
    color: lightColor,
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
      xl: '1.5rem',
    },
    radius: {
      sm: '0.375rem',
      md: '0.5rem',
      lg: '0.75rem',
      full: '9999px',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSizeSm: '0.875rem',
      fontSizeMd: '1rem',
      fontWeightMedium: '500',
    },
    comp: {
      button: {
        radius: '0.5rem',
        fontWeight: '500',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        paddingX: { sm: '0.75rem', md: '1rem', lg: '1.25rem' },
        paddingY: { sm: '0.375rem', md: '0.5rem', lg: '0.625rem' },
        fontSize: { sm: '0.8125rem', md: '0.875rem', lg: '1rem' },
        variants: {
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'var(--semiui-color-primary)',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-muted)',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'var(--semiui-color-destructive)',
          },
          success: {
            background: '#16a34a',
            foreground: '#ffffff',
            border: '#16a34a',
          },
          info: {
            background: '#3b82f6',
            foreground: '#ffffff',
            border: '#3b82f6',
          },
          warn: {
            background: '#d97706',
            foreground: '#ffffff',
            border: '#d97706',
          },
          help: {
            background: '#8b5cf6',
            foreground: '#ffffff',
            border: '#8b5cf6',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'var(--semiui-color-foreground)',
          },
          link: {
            background: 'transparent',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
        },
      },
      input: {
        paddingX: '0.75rem',
        paddingY: '0.5rem',
        radius: '0.5rem',
        fontSize: '0.875rem',
        background: 'var(--semiui-color-background)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'var(--semiui-color-border)',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      select: {
        paddingX: '0.75rem',
        paddingY: '0.5rem',
        radius: '0.5rem',
        fontSize: '0.875rem',
        background: 'var(--semiui-color-background)',
        foreground: 'var(--semiui-color-foreground)',
        placeholderForeground: 'var(--semiui-color-muted-foreground)',
        border: 'var(--semiui-color-border)',
        borderHover: 'var(--semiui-color-muted-foreground)',
        borderFocus: 'var(--semiui-color-ring)',
        focusRing: 'var(--semiui-color-ring)',
        borderInvalid: 'var(--semiui-color-destructive)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'var(--semiui-color-border)',
        panelShadow: '0 8px 24px rgb(15 23 42 / 0.10)',
        panelMaxHeight: '16rem',
        optionForeground: 'var(--semiui-color-foreground)',
        optionBackgroundHover: 'var(--semiui-color-muted)',
        optionBackgroundSelected: 'var(--semiui-color-primary)',
        optionForegroundSelected: 'var(--semiui-color-primary-foreground)',
      },
      switch: {
        trackPadding: '0.125rem',
        trackBorderWidth: '1px',
        radius: 'var(--semiui-radius-full)',
        background: 'var(--semiui-color-muted)',
        backgroundChecked: 'var(--semiui-color-primary)',
        border: 'var(--semiui-color-border)',
        borderChecked: 'var(--semiui-color-primary)',
        thumbBackground: 'var(--semiui-color-background)',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        transitionDuration: '0.15s',
        trackWidth: { sm: '2rem', md: '2.75rem', lg: '3.5rem' },
        trackHeight: { sm: '1.125rem', md: '1.5rem', lg: '1.875rem' },
        thumbSize: { sm: '0.875rem', md: '1.125rem', lg: '1.5rem' },
      },
      checkbox: {
        radius: '0.25rem',
        border: 'var(--semiui-color-border)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundChecked: 'var(--semiui-color-primary)',
        foregroundChecked: 'var(--semiui-color-primary-foreground)',
        focusRing: 'var(--semiui-color-ring)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      radio: {
        border: 'var(--semiui-color-border)',
        borderChecked: 'var(--semiui-color-primary)',
        background: 'var(--semiui-color-background)',
        backgroundDisabled: 'var(--semiui-color-muted)',
        borderDisabled: 'var(--semiui-color-border)',
        dotBackground: 'var(--semiui-color-primary)',
        focusRing: 'var(--semiui-color-ring)',
        size: { sm: '1rem', md: '1.25rem', lg: '1.5rem' },
      },
      popover: {
        background: 'var(--semiui-color-background)',
        border: 'var(--semiui-color-border)',
        shadow: '0 8px 24px rgb(15 23 42 / 0.10)',
        radius: '0.5rem',
        foreground: 'var(--semiui-color-foreground)',
        paddingX: '1rem',
        paddingY: '0.75rem',
      },
      tooltip: {
        background: 'var(--semiui-color-foreground)',
        foreground: 'var(--semiui-color-background)',
        radius: '0.375rem',
        paddingX: '0.5rem',
        paddingY: '0.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
      },
      skeleton: {
        background: 'var(--semiui-color-muted)',
        shimmer:
          'color-mix(in srgb, var(--semiui-color-muted-foreground) 20%, transparent)',
        radius: '0.375rem',
      },
      avatar: {
        background: 'var(--semiui-color-muted)',
        foreground: 'var(--semiui-color-foreground)',
        radius: '0.5rem',
        statusOnline: '#22c55e',
        statusAway: '#f59e0b',
        statusBusy: '#ef4444',
        statusOffline: '#9ca3af',
        size: { sm: '1.75rem', md: '2.5rem', lg: '3.5rem', xl: '5rem' },
        fontSize: {
          sm: '0.625rem',
          md: '0.875rem',
          lg: '1.125rem',
          xl: '1.5rem',
        },
      },
      tag: {
        radius: '0.375rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        paddingX: '0.5rem',
        paddingY: '0.125rem',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background:
              'color-mix(in srgb, var(--semiui-color-primary) 15%, transparent)',
            foreground: 'var(--semiui-color-primary)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-muted-foreground)',
            border: 'transparent',
          },
          destructive: {
            background:
              'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          danger: {
            background:
              'color-mix(in srgb, var(--semiui-color-destructive) 15%, transparent)',
            foreground: 'var(--semiui-color-destructive)',
            border: 'transparent',
          },
          success: {
            background: 'color-mix(in srgb, #16a34a 15%, transparent)',
            foreground: '#16a34a',
            border: 'transparent',
          },
          info: {
            background: 'color-mix(in srgb, #3b82f6 15%, transparent)',
            foreground: '#3b82f6',
            border: 'transparent',
          },
          warn: {
            background: 'color-mix(in srgb, #d97706 15%, transparent)',
            foreground: '#d97706',
            border: 'transparent',
          },
          help: {
            background: 'color-mix(in srgb, #8b5cf6 15%, transparent)',
            foreground: '#8b5cf6',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'transparent',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      breadcrumb: {
        foreground: 'var(--semiui-color-muted-foreground)',
        currentForeground: 'var(--semiui-color-foreground)',
        separatorColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: '0.375rem',
      },
      badge: {
        size: '1.25rem',
        dotSize: '0.625rem',
        fontSize: '0.6875rem',
        ringColor: 'var(--semiui-color-background)',
        variants: {
          default: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          primary: {
            background: 'var(--semiui-color-primary)',
            foreground: 'var(--semiui-color-primary-foreground)',
            border: 'transparent',
          },
          secondary: {
            background: 'var(--semiui-color-muted)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
          },
          destructive: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          danger: {
            background: 'var(--semiui-color-destructive)',
            foreground: 'var(--semiui-color-destructive-foreground)',
            border: 'transparent',
          },
          success: {
            background: '#16a34a',
            foreground: '#ffffff',
            border: 'transparent',
          },
          info: {
            background: '#3b82f6',
            foreground: '#ffffff',
            border: 'transparent',
          },
          warn: {
            background: '#d97706',
            foreground: '#ffffff',
            border: 'transparent',
          },
          help: {
            background: '#8b5cf6',
            foreground: '#ffffff',
            border: 'transparent',
          },
          contrast: {
            background: 'var(--semiui-color-foreground)',
            foreground: 'var(--semiui-color-background)',
            border: 'transparent',
          },
          outline: {
            background: 'var(--semiui-color-background)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'var(--semiui-color-border)',
          },
        },
      },
      pagination: {
        radius: '0.375rem',
        gap: '0.25rem',
        size: '2.25rem',
        border: 'var(--semiui-color-border)',
        background: 'transparent',
        foreground: 'var(--semiui-color-foreground)',
        backgroundHover: 'var(--semiui-color-muted)',
        backgroundActive: 'var(--semiui-color-primary)',
        foregroundActive: 'var(--semiui-color-primary-foreground)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
      },
      rating: {
        filledColor: '#f59e0b',
        emptyColor: 'var(--semiui-color-border)',
        gap: '0',
        size: { sm: '1.25rem', md: '2rem', lg: '2.75rem' },
      },
      accordion: {
        border: 'var(--semiui-color-border)',
        radius: 'var(--semiui-radius-md)',
        headerBackground: 'transparent',
        headerBackgroundHover: 'var(--semiui-color-muted)',
        headerForeground: 'var(--semiui-color-foreground)',
        panelBackground: 'transparent',
        panelForeground: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      tabs: {
        border: 'var(--semiui-color-border)',
        gap: 'var(--semiui-spacing-md)',
        foreground: 'var(--semiui-color-muted-foreground)',
        foregroundActive: 'var(--semiui-color-primary)',
        foregroundDisabled: 'var(--semiui-color-muted-foreground)',
        indicatorColor: 'var(--semiui-color-primary)',
        indicatorThickness: '2px',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        fontWeight: 'var(--semiui-typography-font-weight-medium)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
      },
      stepper: {
        circleSize: '2rem',
        circleBorder: 'var(--semiui-color-border)',
        circleBackground: 'var(--semiui-color-background)',
        circleForeground: 'var(--semiui-color-muted-foreground)',
        circleBackgroundActive: 'var(--semiui-color-primary)',
        circleForegroundActive: 'var(--semiui-color-primary-foreground)',
        circleBackgroundCompleted: 'var(--semiui-color-primary)',
        circleForegroundCompleted: 'var(--semiui-color-primary-foreground)',
        connectorColor: 'var(--semiui-color-border)',
        connectorColorCompleted: 'var(--semiui-color-primary)',
        labelColor: 'var(--semiui-color-muted-foreground)',
        labelColorActive: 'var(--semiui-color-foreground)',
        descriptionColor: 'var(--semiui-color-muted-foreground)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        gap: 'var(--semiui-spacing-sm)',
      },
      slider: {
        trackSize: '0.375rem',
        trackColor: 'var(--semiui-color-muted)',
        fillColor: 'var(--semiui-color-primary)',
        thumbSize: '1.125rem',
        thumbBackground: 'var(--semiui-color-background)',
        thumbBorder: 'var(--semiui-color-primary)',
        thumbBorderFocus: 'var(--semiui-color-ring)',
        tickColor: 'var(--semiui-color-border)',
        tickSize: '0.25rem',
        bubbleBackground: 'var(--semiui-color-foreground)',
        bubbleForeground: 'var(--semiui-color-background)',
      },
      chart: {
        gridColor: 'var(--semiui-color-border)',
        axisLabelColor: 'var(--semiui-color-muted-foreground)',
        axisLabelFontSize: '9px',
        tooltipBackground: 'var(--semiui-color-foreground)',
        tooltipForeground: 'var(--semiui-color-background)',
        tooltipRadius: 'var(--semiui-radius-sm)',
        legendFontSize: 'var(--semiui-typography-font-size-sm)',
        legendGap: 'var(--semiui-spacing-md)',
        lineStrokeWidth: '2',
        areaOpacity: '0.15',
      },
      table: {
        border: 'var(--semiui-color-border)',
        radius: 'var(--semiui-radius-md)',
        headerBackground: 'var(--semiui-color-muted)',
        headerForeground: 'var(--semiui-color-foreground)',
        rowBackground: 'var(--semiui-color-background)',
        rowBackgroundStriped: 'var(--semiui-color-muted)',
        rowBackgroundHover: 'var(--semiui-color-muted)',
        rowBackgroundSelected:
          'color-mix(in srgb, var(--semiui-color-primary) 12%, transparent)',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        cellPaddingX: 'var(--semiui-spacing-md)',
        cellPaddingY: 'var(--semiui-spacing-sm)',
        sortIconColor: 'var(--semiui-color-muted-foreground)',
        sortIconColorActive: 'var(--semiui-color-foreground)',
      },
      colorPicker: {
        svAreaSize: '12rem',
        hueTrackHeight: '0.75rem',
        thumbSize: '1rem',
        hueThumbWidth: '0.75rem',
        presetSize: '1.5rem',
        presetGap: '0.375rem',
        presetBorder: 'var(--semiui-color-border)',
        presetBorderSelected: 'var(--semiui-color-primary)',
      },
      datePicker: {
        daySize: '2.25rem',
        fontSize: 'var(--semiui-typography-font-size-sm)',
        dayForeground: 'var(--semiui-color-foreground)',
        dayForegroundOutsideMonth: 'var(--semiui-color-muted-foreground)',
        dayBackgroundHover: 'var(--semiui-color-muted)',
        dayBackgroundSelected: 'var(--semiui-color-primary)',
        dayForegroundSelected: 'var(--semiui-color-primary-foreground)',
        dayBorderToday: 'var(--semiui-color-primary)',
        navBackgroundHover: 'var(--semiui-color-muted)',
        weekdayForeground: 'var(--semiui-color-muted-foreground)',
        monthLabelForeground: 'var(--semiui-color-foreground)',
      },
      carousel: {
        radius: 'var(--semiui-radius-lg)',
        arrowSize: '2.5rem',
        arrowBackground: 'rgb(0 0 0 / 0.4)',
        arrowBackgroundHover: 'rgb(0 0 0 / 0.6)',
        arrowColor: '#fff',
        dotSize: '0.5rem',
        dotColor: 'var(--semiui-color-border)',
        dotColorActive: 'var(--semiui-color-primary)',
        dotGap: 'var(--semiui-spacing-xs)',
      },
      toast: {
        radius: 'var(--semiui-radius-md)',
        shadow:
          '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        paddingX: 'var(--semiui-spacing-md)',
        paddingY: 'var(--semiui-spacing-sm)',
        gap: 'var(--semiui-spacing-sm)',
        width: '24rem',
        blur: 'blur(12px)',
        variants: {
          default: {
            background:
              'color-mix(in srgb, var(--semiui-color-background) 88%, transparent)',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: 'var(--semiui-color-muted-foreground)',
          },
          success: {
            background:
              'color-mix(in srgb, #22c55e 14%, color-mix(in srgb, var(--semiui-color-background) 88%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#22c55e',
          },
          error: {
            background:
              'color-mix(in srgb, var(--semiui-color-destructive) 14%, color-mix(in srgb, var(--semiui-color-background) 88%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: 'var(--semiui-color-destructive)',
          },
          warning: {
            background:
              'color-mix(in srgb, #f59e0b 14%, color-mix(in srgb, var(--semiui-color-background) 88%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#f59e0b',
          },
          info: {
            background:
              'color-mix(in srgb, #3b82f6 14%, color-mix(in srgb, var(--semiui-color-background) 88%, transparent))',
            foreground: 'var(--semiui-color-foreground)',
            border: 'transparent',
            iconColor: '#3b82f6',
          },
        },
      },
      fileUpload: {
        border: 'var(--semiui-color-border)',
        borderDragOver: 'var(--semiui-color-primary)',
        background: 'transparent',
        backgroundDragOver: 'var(--semiui-color-muted)',
        radius: 'var(--semiui-radius-lg)',
        iconColor: 'var(--semiui-color-muted-foreground)',
        hintColor: 'var(--semiui-color-foreground)',
        acceptColor: 'var(--semiui-color-muted-foreground)',
        itemBackground: 'var(--semiui-color-muted)',
        itemBorder: 'var(--semiui-color-border)',
        itemRadius: 'var(--semiui-radius-md)',
        thumbSize: '2.5rem',
        rejectionColor: 'var(--semiui-color-destructive)',
      },
      dialog: {
        backdropColor: 'rgb(0 0 0 / 0.5)',
        panelBackground: 'var(--semiui-color-background)',
        panelBorder: 'var(--semiui-color-border)',
        radius: 'var(--semiui-radius-lg)',
        shadow:
          '0 24px 48px -12px rgb(15 23 42 / 0.20), 0 12px 24px -12px rgb(15 23 42 / 0.12)',
        headerBorder: 'var(--semiui-color-border)',
        footerBorder: 'var(--semiui-color-border)',
        titleFontSize: '1.125rem',
        titleFontWeight: '700',
        padding: 'var(--semiui-spacing-lg)',
        widths: {
          sm: '24rem',
          md: '32rem',
          lg: '48rem',
          full: 'calc(100vw - 2rem)',
        },
      },
    speedDial: {
      radius: 'var(--semiui-radius-full)',
      shadow: 'var(--semiui-comp-popover-shadow)',
      gap: 'var(--semiui-spacing-md)',
      actionSize: { sm: '1.75rem', md: '2rem', lg: '2.375rem' },
      actionBackground: 'var(--semiui-comp-button-variants-secondary-background)',
      actionForeground: 'var(--semiui-comp-button-variants-secondary-foreground)',
      actionBorder: 'var(--semiui-comp-button-variants-secondary-border)',
      stagger: '40ms',
    },
    fullCalendar: {
      navButtonSize: '2rem',
      navIconSize: '0.85rem',
      toolbarButtonPaddingY: '0.375rem',
      titleFontSize: '1.1rem',
      cellMinHeight: '6rem',
      cellMinHeightWeek: '12rem',
      eventsGap: '0.125rem',
      eventPaddingX: '0.375rem',
      eventPaddingY: '0.125rem',
      eventFontSize: '0.7rem',
    },
    treeTable: {
      checkboxColumnWidth: '2.5rem',
      toggleSize: '1.25rem',
      toggleMarginEnd: '0.125rem',
      toggleIconSize: '0.85rem',
    },
    richTextEditor: {
      toolbarGap: '0.125rem',
      toolSize: '1.75rem',
      toolIconSize: '0.95rem',
      contentHeadingFontSizeLg: '1.5em',
      contentHeadingFontSizeMd: '1.25em',
      contentBlockSpacing: '0.5em',
      contentListIndent: '1.5em',
    },
    timeline: {
      markerIconSize: '0.85rem',
      connectorMinLength: '2rem',
      contentGap: '0.125rem',
    },
    cascadeSelect: {
      panelMinWidth: '12rem',
    },
    contextMenu: {
      panelMinWidth: '12rem',
    },
    autoComplete: {
      inputPaddingEnd: '2rem',
    },
    progressBar: {
      trackHeight: { sm: '0.375rem', md: '0.5rem', lg: '0.75rem' },
      labelFontSize: '0.75rem',
    },
    scrollTop: {
      buttonSize: '2.75rem',
      iconSize: '1.1rem',
    },
    splitButton: {
      menuMinWidth: '10rem',
    },
    imageCropper: {
      gridLineColor: 'rgba(255, 255, 255, 0.6)',
      zoomSliderMaxWidth: '16rem',
    },
    organizationChart: {
      nodeMinWidth: '10rem',
      nodeBackgroundSelected: 'color-mix(in srgb, var(--semiui-color-primary) 12%, transparent)',
      nodeBorderSelected: 'var(--semiui-color-primary)',
      toggleSize: '1.25rem',
      gap: '1.5rem',
    },
    knob: {
      valueFontSize: '1.5rem',
      labelColor: 'var(--semiui-color-muted-foreground)',
      labelFontSize: '0.75rem',
    },
    },
  },
  darkColor,
  icons: {
    loading: { type: 'ng-icon', name: 'lucideLoaderCircle' },
    chevronDown: { type: 'ng-icon', name: 'lucideChevronDown' },
    clear: { type: 'ng-icon', name: 'lucideX' },
    passwordShow: { type: 'ng-icon', name: 'lucideEye' },
    passwordHide: { type: 'ng-icon', name: 'lucideEyeOff' },
    checkboxCheck: { type: 'ng-icon', name: 'lucideCheck' },
    checkboxIndeterminate: { type: 'ng-icon', name: 'lucideMinus' },
    search: { type: 'ng-icon', name: 'lucideSearch' },
    plus: { type: 'ng-icon', name: 'lucidePlus' },
    minus: { type: 'ng-icon', name: 'lucideMinus' },
    avatarFallback: { type: 'ng-icon', name: 'lucideUser' },
    rating: { type: 'ng-icon', name: 'lucideStar' },
    upload: { type: 'ng-icon', name: 'lucideUpload' },
    file: { type: 'ng-icon', name: 'lucideFile' },
    toastSuccess: { type: 'ng-icon', name: 'lucideCircleCheck' },
    toastError: { type: 'ng-icon', name: 'lucideCircleX' },
    toastWarning: { type: 'ng-icon', name: 'lucideTriangleAlert' },
    toastInfo: { type: 'ng-icon', name: 'lucideInfo' },
  },
};
